// curriculum.js — コード学習の内容（全52パート・4章立て）。docs/curriculum.md と対応。
// スライド要素: heading / body / staff / staffOpts / key(下部ピアノの調) / keys(ハイライト)
//              / voicing(実音の積み方ハイライト) / listen / practice
// staff の各要素: "C4" / ["C4","E4","G4"](和音) / {chord:[...],label} / {chord:{root,type},label}
// practice: { notes:[offset] } | { chords:[{root,type}] } | { voicings:[[offset...]] }, label, ...

const MAJ = [0, 2, 4, 5, 7, 9, 11, 12];          // メジャースケール
const NMIN = [0, 2, 3, 5, 7, 8, 10, 12];         // ナチュラルマイナー
const HMIN = [0, 2, 3, 5, 7, 8, 11, 12];         // ハーモニックマイナー

// 和音の楽譜エントリを手早く作るヘルパー
function ch(root, type, label) { return { chord: { root: root, type: type }, label: label }; }

const CURRICULUM = [
  { title: "Part 1 さまざまな音名と音程", chapter: "準備編", slides: [
    { heading: "音名（幹音）", key: "C",
      body: ["ピアノの白鍵の音は、下から ド・レ・ミ・ファ・ソ・ラ・シ。", "音楽理論では、これを英語で C・D・E・F・G・A・B と呼びます。"],
      staff: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"], staffOpts: { solfege: true },
      keys: ["C4", "D4", "E4", "F4", "G4", "A4", "B4"],
      listen: { notes: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"], seq: true } },
    { heading: "半音と全音", key: "C",
      body: ["となりの鍵盤（黒鍵もふくむ）までの距離が「半音」、半音2つ分が「全音」です。", "半音は黒鍵をはさむとは限りません。ミ→ファ・シ→ドは白鍵どうしでも半音です。"],
      staff: ["C4", "C#4", "D4", "E4", "F4"],
      staffOpts: { brackets: [{ from: 0, to: 1, text: "半音" }, { from: 2, to: 3, text: "全音" }, { from: 3, to: 4, text: "半音" }] },
      keys: ["C4", "C#4", "D4", "E4", "F4"] },
    { heading: "変化記号 ♯・♭・♮", key: "C",
      body: ["音を半音動かす記号が「変化記号」。♯（シャープ）は半音上げ、♭（フラット）は半音下げ、♮（ナチュラル）はもとに戻します。", "白鍵のあいだの黒鍵は、こうしてできる音。C♯ と E♭ は黒鍵、♮ は変化を取り消して白鍵の E に戻します。"],
      staff: [{ name: "C4", label: "C" }, { name: "C#4", label: "C♯" }, { name: "E4", label: "E" }, { name: "Eb4", label: "E♭" }, { name: "E4", label: "E♮" }],
      staffOpts: { brackets: [{ from: 0, to: 1, text: "♯ 半音上" }, { from: 2, to: 3, text: "♭ 半音下" }, { from: 3, to: 4, text: "♮ 戻す" }] },
      keys: ["C4", "C#4", "E4", "Eb4"] },
    { heading: "異名同音", key: "C",
      body: ["同じ高さの音でも、書き方によって名前が変わります。", "たとえば C♯ と D♭ は同じ鍵盤の音。E♯＝F、B♯＝C なども同じ仲間です。"],
      staff: [{ name: "C#4", label: "C♯=D♭" }], keys: ["C#4"] },
    { heading: "音程＝2音の距離（度数）", key: "C",
      body: ["2つの音のへだたりを「度数」で表します。同じ音が1度、となりが2度…と数えます。", "数えるときは両端の音もふくめます。例：C から E は C・D・E で「3度」。"],
      staff: ["C4", "E4"], staffOpts: { brackets: [{ from: 0, to: 1, text: "3度" }] }, keys: ["C4", "E4"],
      listen: { notes: ["C4", "E4"], seq: false } },
    { heading: "完全・長短・増減", key: "C",
      body: ["1・4・5・8度の音程は「完全」、2・3・6・7度は「長・短」と呼び分けます。", "そこから半音広げると「増」、半音せまくすると「減」になります。"],
      staff: ["C4", "F4", "G4"], staffOpts: { brackets: [{ from: 0, to: 1, text: "完全4度" }] }, keys: ["C4", "F4", "G4"] },
    { heading: "練習：ドレミファソラシド", key: "C",
      body: ["下の鍵盤で、白鍵を左から順に弾いてドレミを鳴らしてみましょう。", "「キー（左端の音）」を変えると、そのまま各調で練習できます。"],
      practice: { notes: MAJ, label: "ドレミファソラシド" } },
    { heading: "練習：音程（度数）を弾く", key: "C",
      body: ["主音 C から、3度(E)・4度(F)・5度(G)・8度(C) と、へだたりを広げながら弾いてみましょう。", "同じ「度数」でも、鍵盤上の距離（半音の数）の違いを感じてください。"],
      practice: { notes: [0, 4, 5, 7, 12], label: "度数（3・4・5・8度）" } },
  ] },

  { title: "Part 2 インターバルとスケール", slides: [
    { heading: "スケールとは", key: "C",
      body: ["スケール（音階）は、主音から1オクターブ上まで、決まった順で音を並べたものです。", "曲で使う音の土台、いわば「ものさし」になります。"],
      staff: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"],
      keys: ["C4", "D4", "E4", "F4", "G4", "A4", "B4"], listen: { notes: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"], seq: true } },
    { heading: "メジャースケールの並び", key: "C",
      body: ["明るい響きのメジャースケールは「全・全・半・全・全・全・半」の順で並びます。", "半音になるのは「ミ→ファ」と「シ→ド」の2か所だけです。"],
      staff: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"], staffOpts: { solfege: true } },
    { heading: "Cメジャースケール",
      example: { tempo:132, chords:[{offs:[0,4,7],beats:8},{offs:[5,9,12],beats:2},{offs:[0,4,7],beats:2},{offs:[7,11,14],beats:2},{offs:[0,4,7],beats:2}], melody:[[0,1],[0,1],[7,1],[7,1],[9,1],[9,1],[7,2],[5,1],[5,1],[4,1],[4,1],[2,1],[2,1],[0,2]], label:"きらきら星（Cメジャー）" }, key: "C",
      body: ["Cメジャーは白鍵だけ（C D E F G A B C）で弾ける、いちばん基本のスケールです。"],
      keys: ["C4", "D4", "E4", "F4", "G4", "A4", "B4"],
      listen: { notes: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"], seq: true } },
    { heading: "他キーは ♯/♭ が要る", key: "G",
      body: ["同じ「全全半…」の並びを G から始めると、7番目の音に F♯ が必要になります。", "こうして Gメジャー（G A B C D E F♯ G）ができます。"],
      staff: ["G4", "A4", "B4", "C5", "D5", "E5", "F#5", "G5"], keys: ["G3", "A3", "B3", "C4", "D4", "E4", "F#4"] },
    { heading: "練習：メジャースケール（各キー）", key: "C",
      body: ["白鍵を左から順に弾くとメジャースケールになります。", "「キー」を変えて、いろいろな調で弾いてみましょう。"],
      practice: { notes: MAJ, label: "メジャースケール" } },
  ] },

  { title: "Part 3 さまざまなスケール", slides: [
    { heading: "ナチュラルマイナー",
      example: { tempo:100, chords:[{offs:[0,3,7],beats:4},{offs:[5,8,12],beats:2},{offs:[7,10,14],beats:2},{offs:[0,3,7],beats:4}], melody:[[0,1],[3,1],[7,2],[5,1],[3,1],[2,2],[3,1],[2,1],[0,2]], label:"短調の哀愁（Am i-iv-v-i）" }, key: "A",
      body: ["暗い響きのマイナースケールは「全・半・全・全・半・全・全」の並びです。", "Aマイナーは白鍵だけ（A B C D E F G A）で弾けます。"],
      staff: ["A3", "B3", "C4", "D4", "E4", "F4", "G4", "A4"], keys: ["A3", "B3", "C4", "D4", "E4", "F4", "G4"],
      listen: { notes: ["A3", "B3", "C4", "D4", "E4", "F4", "G4", "A4"], seq: true } },
    { heading: "短調化（メジャー→マイナー）", key: "C",
      body: ["メジャースケールの 3・6・7番目の音を半音下げると、ナチュラルマイナーになります。", "たった3つの音で、明るい響きが暗い響きに変わります。"],
      staff: ["C4", "D4", "Eb4", "F4", "G4", "Ab4", "Bb4", "C5"], keys: ["C4", "D4", "Eb4", "F4", "G4", "Ab4", "Bb4"],
      listen: { notes: ["C4", "D4", "Eb4", "F4", "G4", "Ab4", "Bb4", "C5"], seq: true } },
    { heading: "平行調（relative）", key: "C",
      body: ["使う音がまったく同じで、中心になる音（主音）だけが違う関係を「平行調」といいます。", "Cメジャーと Aマイナーは同じ白鍵。中心が C か A かの違いだけです。"],
      staff: [ch("C", "maj", "C"), ch("A", "min", "Am")], keys: ["C4", "D4", "E4", "F4", "G4", "A4", "B4"] },
    { heading: "同主調（parallel）", key: "C",
      body: ["主音が同じで、メジャーとマイナーだけが違う関係を「同主調」といいます。", "Cメジャーと Cマイナー。他調から音を借りる（借用）ときの入り口です。"],
      staff: [ch("C", "maj", "C"), ch("C", "min", "Cm")], keys: ["C4", "Eb4", "G4"] },
    { heading: "練習：Aマイナースケール", key: "A",
      body: ["マイナースケールの並びで弾いてみましょう（キーAなら左端が「ラ」）。"],
      practice: { notes: NMIN, label: "ナチュラルマイナースケール" } },
    { heading: "練習：同主調の明暗（C→Cm）", key: "C",
      body: ["主音はそのまま、C（明るい）→ Cm（暗い）と弾き比べてみましょう。", "3度の音（E→E♭）が変わるだけで、響きの色がガラッと変わります。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "C", type: "min" }], label: "同主調（C / Cm）" } },
  ] },

  // ===== 準備編 つづき（Part 4-5：五度圏・音色）=====
  { title: "Part 4 五度圏と調号", slides: [
    { heading: "調号とは", key: "G",
      body: ["曲の間ずっと♯や♭が付く音を、毎回書かずに楽譜の左端へまとめたものが「調号」です。", "たとえば Gメジャーは F にいつも♯が付くので、調号は♯1つになります。"],
      staff: ["G4", "A4", "B4", "C5", "D5", "E5", "F#5", "G5"], keys: ["G3", "A3", "B3", "C4", "D4", "E4", "F#4"] },
    { heading: "♯が増える順番", key: "C",
      body: ["♯は必ず F♯→C♯→G♯→D♯→A♯… の順で増えます（5度ずつ上がる並び）。", "キーを5度上げるたびに♯が1つ増えます：C→G→D→A→E→B。"],
      staff: ["F#4", "C#5", "G#5", "D#5", "A#5"], keys: ["F#4", "C#4", "G#4", "D#4", "A#4"] },
    { heading: "♭が増える順番", key: "C",
      body: ["♭は B♭→E♭→A♭→D♭→G♭… の順（♯と逆＝4度ずつ上がる並び）。", "キーを4度上げるたびに♭が1つ増えます：C→F→B♭→E♭→A♭。"],
      staff: ["Bb4", "Eb5", "Ab5", "Db5", "Gb5"], keys: ["Bb4", "Eb4", "Ab4", "Db4", "Gb4"] },
    { heading: "主要キーの調号（早見）", key: "C",
      body: ["♯系：G=♯1・D=♯2・A=♯3・E=♯4。 ♭系：F=♭1・B♭=♭2・E♭=♭3・A♭=♭4。", "「一番右の♯の半音上」がメジャーの主音。♭系は「最後から2つ目の♭」が主音です。"],
      staff: [ch("C", "maj", "C:0"), ch("G", "maj", "G:♯1"), ch("D", "maj", "D:♯2"), ch("F", "maj", "F:♭1"), ch("Bb", "maj", "B♭:♭2")] },
    { heading: "平行調（同じ調号）", key: "A",
      body: ["同じ調号を共有するメジャーとマイナーを「平行調」といいます（主音は短3度ちがい）。", "調号なし＝C と Am。♯1つ＝G と Em。"],
      staff: [ch("C", "maj", "C"), ch("A", "min", "Am")], keys: ["A3", "B3", "C4", "D4", "E4", "F4", "G4"] },
    { heading: "練習：五度圏を回る", key: "C",
      body: ["C→G→D→A→E→B と、各キーの主音を弾いてみましょう（五度圏の右回り）。"],
      practice: { notes: [0, 7, 2, 9, 4, 11], label: "五度圏の主音（C G D A E B）" } },
  ] },

  { title: "Part 5 倍音と音色", slides: [
    { heading: "音の三要素", key: "C",
      body: ["音は「大きさ（振幅）」「高さ（周波数）」「音色（波形）」の3つで決まります。", "同じ高さ・大きさでも、波形が変われば楽器の違いとして聞こえます。"],
      staff: ["C4"], keys: ["C4"] },
    { heading: "倍音列", key: "C",
      body: ["1つの音の上には、整数倍の周波数の音（倍音）がふくまれています。", "C を基音にすると、上に C・G・C・E・G・B♭・C… と倍音が積み上がります。"],
      staff: ["C3", "C4", "G4", "C5", "E5", "G5", "Bb5", "C6"], keys: ["C4", "E4", "G4", "Bb4"] },
    { heading: "低い倍音はメジャーコード", key: "C",
      body: ["下の方の倍音を拾うと、ちょうど C・E・G＝メジャーコードになります。", "コードが自然で心地よく響くのは、この倍音の並びが理由のひとつです。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }], keys: ["C4", "E4", "G4"] },
    { heading: "オクターブ＝周波数2倍", key: "C",
      body: ["ある音の1オクターブ上は、周波数がちょうど2倍。だから同じ音名（C→C）に聞こえます。"],
      staff: ["C4", "C5"], keys: ["C4"] },
    { heading: "エンベロープ（ADSR）", key: "C",
      body: ["音量の時間変化を4つで表すのが ADSR：Attack(立ち上がり)・Decay(減衰)・Sustain(持続)・Release(余韻)。", "同じ波形でも ADSR が変わると、ピアノ的にも弦的にも聞こえます。"],
      staff: ["C4"], keys: ["C4"] },
    { heading: "練習：倍音がつくる和音", key: "C",
      body: ["低い倍音がつくる「ド・ミ・ソ」を弾いてみましょう。"],
      practice: { notes: [0, 4, 7, 12], label: "倍音のド・ミ・ソ・ド" } },
  ] },

  // ===== メロディ編（Part 6-13）=====
  { title: "Part 6 メロディの基礎", chapter: "メロディ編", slides: [
    { heading: "モチーフ：提示・展開・解消", key: "C",
      body: ["メロディは短い動機（モチーフ）を「提示」し、変形して「展開」、反復を止めて「解消（終止）」します。", "ひとつのアイデアをふくらませるのが、覚えやすいメロディのコツです。"],
      staff: ["E4", "G4", "C5", "G4", "E4", "C4"], keys: ["C4", "E4", "G4"] },
    { heading: "順次進行と跳躍進行", key: "C",
      body: ["となりの音へ動くのが「順次進行」（なめらか）、離れた音へ跳ぶのが「跳躍進行」（劇的）。", "上行は緊張、下行は安らぎ。とくに跳躍上行がいちばんドラマチックです。"],
      staff: ["C4", "D4", "E4", "F4", "G4"], staffOpts: { brackets: [{ from: 0, to: 1, text: "順次" }] }, keys: ["C4", "D4", "E4", "F4", "G4"] },
    { heading: "跳躍（大きく跳ぶ）", key: "C",
      body: ["同じ音でも、間を跳び越すと勢いが出ます。C から G、C へと跳んでみましょう。"],
      staff: ["C4", "G4", "C5"], staffOpts: { brackets: [{ from: 0, to: 1, text: "5度跳躍" }] }, keys: ["C4", "G4"] },
    { heading: "音名と階名（相対で考える）", key: "C",
      body: ["同じ「C」でも、Cメジャーでは主音（ド）、Fメジャーでは5番目の音（ソ）。", "大切なのは絶対の高さより「キーの中心から見た位置」です。"],
      staff: ["C4", "G4"], keys: ["C4", "G4"] },
    { heading: "空白（休符）の効果", key: "C",
      body: ["音を止める「空白」も表現です。無音が静けさや語りかけを生みます（引き算の美学）。"],
      staff: ["E4", { rest: true, beats: 2 }, "C4"], keys: ["C4", "E4"] },
    { heading: "練習：順次進行のメロディ", key: "C",
      body: ["となりの音へなめらかに動く順次進行のメロディを弾いてみましょう。"],
      practice: { notes: [0, 2, 4, 5, 4, 2, 0], label: "順次進行（ドレミファミレド）" } },
    { heading: "練習：跳躍進行のメロディ", key: "C",
      body: ["今度は音を跳び越えて動く跳躍進行。ド→ソ→ド→ミ と、勢いのある跳躍を弾いてみましょう。"],
      practice: { notes: [0, 7, 12, 4, 7, 0], label: "跳躍進行（ド→ソ→ド→ミ）" } },
  ] },

  { title: "Part 7 傾性と調性引力", slides: [
    { heading: "安定音と不安定音", key: "C",
      body: ["メジャースケールは、安定音 ド・ミ・ソ（C E G）と、不安定音 レ・ファ・ラ・シ（D F A B）に分かれます。", "不安定音は、近くの安定音へ「進みたがる」性質（傾性）を持ちます。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "安定 C E G" }], keys: ["C4", "E4", "G4"] },
    { heading: "導音の解決（シ→ド）",
      example: { tempo:96, chords:[{offs:[7,11,14,17],beats:4},{offs:[0,4,7,12],beats:2}], melody:[[7,1],[11,1],[14,1],[11,1],[12,2]], label:"V7→I（導音シ→ド）" }, key: "C",
      body: ["第7音 シ(B) は、半音上の主音 ド(C) へ強く引かれます。これが終止感の正体です。"],
      staff: ["B4", "C5"], staffOpts: { brackets: [{ from: 0, to: 1, text: "半音で解決" }] }, keys: ["B4", "C4"] },
    { heading: "ファ→ミ の解決", key: "C",
      body: ["強い傾性を持つのは F と B。半音で隣の安定音へ解決します（F→E、B→C）。"],
      staff: ["F4", "E4"], staffOpts: { brackets: [{ from: 0, to: 1, text: "F→E" }] }, keys: ["F4", "E4"] },
    { heading: "収束と発散", key: "C",
      body: ["中心音 C へ近づく動きが「収束」（弛緩）、遠ざかる動きが「発散」（緊張）。", "G→A→B→C も F→E→D→C も、向きは逆でも同じ『Cへの収束』です。"],
      staff: ["G4", "A4", "B4", "C5"], keys: ["C4", "G4", "A4", "B4"] },
    { heading: "カーネル（各音の個性）", key: "C",
      body: ["C＝完全な着地点、G＝次に安定、E＝情感、D＝浮遊、F＝最も不安定で下がりたい、B＝ドへ上がりたい。", "各音の『キャラ』を知ると、狙って感情を作れます。"],
      staff: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"], staffOpts: { solfege: true } },
    { heading: "練習：傾性を解決する", key: "C",
      body: ["不安定音を、すぐ近くの安定音へ解決させます。シ→ド・ファ→ミ・レ→ド・ラ→ソ を順に弾きましょう。", "どれも「動きたがる音→落ち着く音」。解決した瞬間の安心感を味わってください。"],
      practice: { notes: [11, 12, 5, 4, 2, 0, 9, 7], label: "傾性の解決（シ→ド・ファ→ミ・レ→ド・ラ→ソ）" } },
  ] },

  { title: "Part 8 ペンタトニックと民族音階", slides: [
    { heading: "四七抜き＝メジャーペンタ",
      example: { tempo:120, chords:[{offs:[0,4,7],beats:8}], melody:[[0,0.5],[2,0.5],[4,1],[7,0.5],[9,0.5],[7,1],[9,0.5],[7,0.5],[4,0.5],[2,0.5],[0,2]], label:"メジャーペンタのリック" }, key: "C",
      body: ["メジャースケールから傾性の強い ファ(4)・シ(7) を抜いた5音が「メジャーペンタトニック」。", "C D E G A。半音がなく、明るく外れにくい万能スケールです。"],
      staff: ["C4", "D4", "E4", "G4", "A4", "C5"], keys: ["C4", "D4", "E4", "G4", "A4"] },
    { heading: "マイナーペンタ",
      example: { tempo:100, chords:[{offs:[0,3,7],beats:8}], melody:[[7,1],[10,1],[7,1],[5,1],[3,1],[5,1],[3,1],[0,1]], label:"マイナーペンタのリック" }, key: "A",
      body: ["同じ5音を ラ(A) 中心にすると「マイナーペンタトニック」。A C D E G。", "ロックやブルースのソロの土台になります。"],
      staff: ["A3", "C4", "D4", "E4", "G4", "A4"], keys: ["A3", "C4", "D4", "E4", "G4"] },
    { heading: "琉球音階",
      example: { tempo:96, chords:[{offs:[0,4,7],beats:8}], melody:[[0,1],[4,1],[7,1],[11,1],[7,1],[5,1],[4,1],[0,1]], label:"琉球音階の旋律" }, key: "C",
      body: ["第2音・第6音を抜いた C E F G B。半音進行が多く、沖縄・ガムラン風の神秘的な響き。"],
      staff: ["C4", "E4", "F4", "G4", "B4", "C5"], keys: ["C4", "E4", "F4", "G4", "B4"] },
    { heading: "四抜き音階", key: "C",
      body: ["ファ(4) だけを抜いた C D E G A B。シ→ドの解決は残しつつ、ポップスで多用されます。"],
      staff: ["C4", "D4", "E4", "G4", "A4", "B4", "C5"], keys: ["C4", "D4", "E4", "G4", "A4", "B4"] },
    { heading: "練習：メジャーペンタ", key: "C",
      body: ["ファとシを抜いた5音（ド・レ・ミ・ソ・ラ）を弾いてみましょう。"],
      practice: { notes: [0, 2, 4, 7, 9, 12], label: "メジャーペンタトニック" } },
    { heading: "練習：マイナーペンタ", key: "A",
      body: ["同じ5音を主音 A から並べたマイナーペンタ（A C D E G）。ロック／ブルースのソロの土台です。"],
      practice: { notes: [0, 3, 5, 7, 10, 12], label: "マイナーペンタトニック" } },
    { heading: "練習：琉球音階", key: "C",
      body: ["第2・6音を抜いた C E F G B。半音を含む、沖縄・ガムラン風の神秘的な響きを弾いてみましょう。"],
      practice: { notes: [0, 4, 5, 7, 11, 12], label: "琉球音階" } },
    { heading: "練習：四抜き音階", key: "C",
      body: ["ファ(4)だけを抜いた C D E G A B。シ→ドの解決を残した、ポップスで定番の5＋2音です。"],
      practice: { notes: [0, 2, 4, 7, 9, 11, 12], label: "四抜き音階" } },
  ] },

  { title: "Part 9 三つの短音階", slides: [
    { heading: "ナチュラルマイナー", key: "C",
      body: ["基本の短音階。C D E♭ F G A♭ B♭。第7音が主音の全音下なので、終止感は控えめです。"],
      staff: ["C4", "D4", "Eb4", "F4", "G4", "Ab4", "Bb4", "C5"], keys: ["C4", "D4", "Eb4", "F4", "G4", "Ab4", "Bb4"] },
    { heading: "ハーモニックマイナー",
      example: { tempo:100, chords:[{offs:[0,3,7],beats:4},{offs:[7,11,14,17],beats:2},{offs:[0,3,7],beats:2}], melody:[[0,1],[7,1],[8,1.5],[11,0.5],[12,2],[11,1],[8,1]], label:"増2度の異国情緒（A♭→B）" }, key: "C",
      body: ["第7音を半音上げて導音 B を作った音階。C D E♭ F G A♭ B。", "A♭→B が増2度になり、エキゾチックな響きが生まれます。"],
      staff: ["C4", "D4", "Eb4", "F4", "G4", "Ab4", "B4", "C5"], keys: ["C4", "D4", "Eb4", "F4", "G4", "Ab4", "B4"] },
    { heading: "メロディックマイナー（上行）",
      example: { tempo:112, chords:[{offs:[0,3,7,11],beats:8}], melody:[[7,1],[9,1],[11,1],[12,1],[9,1],[7,1],[3,1],[0,1]], label:"メロディックマイナー上行" }, key: "C",
      body: ["第6・7音の両方を上げて増2度を解消。C D E♭ F G A B（上行）。", "なめらかで、下行では普通のナチュラルに戻すのが古典的な使い方です。"],
      staff: ["C4", "D4", "Eb4", "F4", "G4", "A4", "B4", "C5"], keys: ["C4", "D4", "Eb4", "F4", "G4", "A4", "B4"] },
    { heading: "3つのちがいは第6・7音", key: "C",
      body: ["3種の違いは第6音(A♭/A)と第7音(B♭/B)だけ。導音 B が終止感を生みます。"],
      staff: ["Ab4", "Bb4", "A4", "B4"], keys: ["Ab4", "Bb4", "A4", "B4"] },
    { heading: "練習：ナチュラルマイナー", key: "C",
      body: ["まずは基本の並び（第6音 A♭・第7音 B♭）。終止感がひかえめな、素朴な短音階です。"],
      practice: { notes: [0, 2, 3, 5, 7, 8, 10, 12], label: "ナチュラルマイナー" } },
    { heading: "練習：ハーモニックマイナー", key: "C",
      body: ["導音 B を持つハーモニックマイナーを弾いてみましょう（A♭→B の増2度に注目）。"],
      practice: { notes: [0, 2, 3, 5, 7, 8, 11, 12], label: "ハーモニックマイナー" } },
    { heading: "練習：メロディックマイナー（上行）", key: "C",
      body: ["第6・7音の両方を上げた並び（A・B）。増2度が消え、なめらかに歌える上行形です。"],
      practice: { notes: [0, 2, 3, 5, 7, 9, 11, 12], label: "メロディックマイナー（上行）" } },
  ] },

  { title: "Part 10 ブルーノートと特殊音階", slides: [
    { heading: "ブルーノート",
      example: { tempo:96, chords:[{offs:[0,4,7,10],beats:8}], melody:[[0,0.5],[3,0.5],[4,1],[3,0.5],[0,0.5],[10,1],[7,0.5],[6,0.5],[7,1],[3,0.5],[0,1.5]], label:"ブルースのリック（♭3♭5♭7）" }, key: "C",
      body: ["メジャーの3・5・7度を半音下げた音（♭3=E♭、♭5=G♭、♭7=B♭）が「ブルーノート」。", "伴奏は普通のまま、メロディだけ下げると哀愁とブルース感が出ます。"],
      staff: ["Eb4", "Gb4", "Bb4"], keys: ["Eb4", "Gb4", "Bb4"] },
    { heading: "クロマチック・アプローチ", key: "C",
      body: ["スケール外の半音を経過音として挟み、半音でコードトーンへ解決します。", "例：E→D♯→E。D♯ が E への人工的な導音になります。"],
      staff: ["E4", "D#4", "E4"], staffOpts: { brackets: [{ from: 1, to: 2, text: "半音で解決" }] }, keys: ["E4", "D#4"] },
    { heading: "ホールトーンスケール",
      example: { tempo:100, chords:[{offs:[0,4,8],beats:8}], melody:[[0,1],[2,1],[4,1],[6,1],[8,1],[10,1],[8,1],[6,1]], label:"ホールトーンの浮遊感" }, key: "C",
      body: ["全音だけで1オクターブを6等分した対称音階。C D E F♯ G♯ A♯。", "半音も完全5度もなく、無重力・幻想的・SF的な浮遊感を生みます。"],
      staff: ["C4", "D4", "E4", "F#4", "G#4", "A#4", "C5"], keys: ["C4", "D4", "E4", "F#4", "G#4", "A#4"] },
    { heading: "練習：ブルーススケール", key: "C",
      body: ["マイナーペンタに♭5(G♭)を足した C E♭ F G♭ G B♭。♭5を軽く通り過ぎるとブルース感が出ます。"],
      practice: { notes: [0, 3, 5, 6, 7, 10, 12], label: "ブルーススケール（♭5入り）" } },
    { heading: "練習：クロマチック・アプローチ", key: "C",
      body: ["半音下から狙いの音へ。E→D♯→E、G→F♯→G と、半音の経過音でコードトーンへ解決させましょう。"],
      practice: { notes: [4, 3, 4, 7, 6, 7], label: "クロマチック・アプローチ" } },
    { heading: "練習：ホールトーン", key: "C",
      body: ["全音ずつ上がるホールトーンスケールを弾いてみましょう。"],
      practice: { notes: [0, 2, 4, 6, 8, 10, 12], label: "ホールトーンスケール" } },
  ] },

  { title: "Part 11 教会旋法（明るい旋法）", slides: [
    { heading: "教会旋法とは", key: "C",
      body: ["同じ音の並びでも「どの音を中心にするか」で7つの雰囲気（旋法）が生まれます。", "ここでは中心を C にそろえて、明るい系の旋法を比べます。"],
      staff: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"], staffOpts: { solfege: true } },
    { heading: "アイオニアン＝メジャー", key: "C",
      body: ["いちばん基準になる明るい旋法。C D E F G A B。ふつうのメジャースケールです。"],
      staff: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"], keys: ["C4", "D4", "E4", "F4", "G4", "A4", "B4"] },
    { heading: "リディアン（♯4）",
      example: { tempo:112, chords:[{offs:[0,4,7,11],beats:8}], melody:[[7,1],[9,1],[11,1],[9,1],[6,1],[7,1],[6,1],[7,1]], label:"リディアン（♯4=F♯）の浮遊感" }, key: "C",
      body: ["第4音を半音上げた旋法。C D E F♯ G A B。", "増4度 F♯ が、明るさに浮遊感・夢幻的な色を加えます。"],
      staff: ["C4", "D4", "E4", "F#4", "G4", "A4", "B4", "C5"], keys: ["C4", "D4", "E4", "F#4", "G4", "A4", "B4"] },
    { heading: "ミクソリディアン（♭7）",
      example: { tempo:116, chords:[{offs:[0,4,7,10],beats:8}], melody:[[7,1],[10,1],[7,1],[4,1],[5,1],[4,1],[2,1],[0,1]], label:"ミクソリディアン（♭7）" }, key: "C",
      body: ["第7音を半音下げた旋法。C D E F G A B♭。", "♭7 が導音の緊張をやわらげ、明るく豪快（ブルース／ロック）な響きに。"],
      staff: ["C4", "D4", "E4", "F4", "G4", "A4", "Bb4", "C5"], keys: ["C4", "D4", "E4", "F4", "G4", "A4", "Bb4"] },
    { heading: "練習：リディアン", key: "C",
      body: ["♯4(F♯) を含むリディアンを弾いて、浮遊する明るさを感じましょう。"],
      practice: { notes: [0, 2, 4, 6, 7, 9, 11, 12], label: "リディアン（♯4）" } },
    { heading: "練習：ミクソリディアン", key: "C",
      body: ["♭7(B♭) を持つミクソリディアン（C D E F G A B♭）。導音の緊張がやわらぐ、明るく豪快な旋法です。"],
      practice: { notes: [0, 2, 4, 5, 7, 9, 10, 12], label: "ミクソリディアン（♭7）" } },
  ] },

  { title: "Part 12 教会旋法（暗い旋法）", slides: [
    { heading: "ドリアン（♮6）",
      example: { tempo:108, chords:[{offs:[0,3,7,10],beats:8}], melody:[[0,1],[3,1],[5,1],[9,1.5],[7,0.5],[5,1],[3,1],[0,1]], label:"ドリアン（♮6=A）の旋律" }, key: "C",
      body: ["ナチュラルマイナーの第6音だけを上げた旋法。C D E♭ F G A B♭。", "暗さの中に明るい6度(A)が差し込む、ケルト／ジャズ的な浮遊感。"],
      staff: ["C4", "D4", "Eb4", "F4", "G4", "A4", "Bb4", "C5"], keys: ["C4", "D4", "Eb4", "F4", "G4", "A4", "Bb4"] },
    { heading: "エオリアン＝ナチュラルマイナー", key: "C",
      body: ["暗い系の基準。C D E♭ F G A♭ B♭。ふつうのナチュラルマイナーです。"],
      staff: ["C4", "D4", "Eb4", "F4", "G4", "Ab4", "Bb4", "C5"], keys: ["C4", "D4", "Eb4", "F4", "G4", "Ab4", "Bb4"] },
    { heading: "フリジアン（♭2）",
      example: { tempo:104, chords:[{offs:[0,3,7],beats:8}], melody:[[0,1],[1,1],[3,1],[1,1],[0,1],[3,0.5],[1,0.5],[0,2]], label:"フリジアン（♭2）のスペイン感" }, key: "C",
      body: ["第2音を半音下げた旋法。C D♭ E♭ F G A♭ B♭。", "主音の半音上 D♭ が『へばりつく』ような、スペイン風・ダークな響き。"],
      staff: ["C4", "Db4", "Eb4", "F4", "G4", "Ab4", "Bb4", "C5"], keys: ["C4", "Db4", "Eb4", "F4", "G4", "Ab4", "Bb4"] },
    { heading: "ロクリアン（♭5）",
      example: { tempo:96, chords:[{offs:[0,3,6],beats:8}], melody:[[0,1],[3,1],[6,1],[5,1],[3,1],[1,1],[0,2]], label:"ロクリアン（♭5）の不安定" }, key: "C",
      body: ["最も暗く不安定な旋法。C D♭ E♭ F G♭ A♭ B♭。減5度 G♭ で主和音すら濁ります。"],
      staff: ["C4", "Db4", "Eb4", "F4", "Gb4", "Ab4", "Bb4", "C5"], keys: ["C4", "Db4", "Eb4", "F4", "Gb4", "Ab4", "Bb4"] },
    { heading: "明るい順に並べる", key: "C",
      body: ["リディアン→アイオニアン→ミクソリディアン→ドリアン→エオリアン→フリジアン→ロクリアン。", "特徴音が1つずつ変わり、明→暗へグラデーションします。"],
      staff: ["F#4", "B4", "Bb4", "A4", "Ab4", "Db4", "Gb4"] },
    { heading: "練習：ドリアン", key: "C",
      body: ["暗い中に明るい6度(A)を持つドリアン（♮6）を弾いてみましょう。"],
      practice: { notes: [0, 2, 3, 5, 7, 9, 10, 12], label: "ドリアン（♮6）" } },
    { heading: "練習：フリジアン", key: "C",
      body: ["♭2(D♭) が主音にへばりつく、スペイン風・ダークな旋法（C D♭ E♭ F G A♭ B♭）。"],
      practice: { notes: [0, 1, 3, 5, 7, 8, 10, 12], label: "フリジアン（♭2）" } },
    { heading: "練習：ロクリアン", key: "C",
      body: ["♭5(G♭) を持つ最も不安定な旋法（C D♭ E♭ F G♭ A♭ B♭）。主和音すら濁る響きを確かめましょう。"],
      practice: { notes: [0, 1, 3, 5, 6, 8, 10, 12], label: "ロクリアン（♭5）" } },
  ] },

  { title: "Part 13 シェル理論とハモリ", slides: [
    { heading: "メロディの水平と垂直", key: "C",
      body: ["メロディは「時間の流れ（水平）」と「同時に鳴るコードとの関係（垂直）」の両面を持ちます。", "コードトーンは澄み、非コードトーンは濁る——この濁りが表情になります。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }], keys: ["C4", "E4", "G4"] },
    { heading: "シェル＝コードに対する度数", key: "C",
      body: ["メロディ音がコードの何度かで性質が決まります。Cコード上では C=1・E=3・G=5・B=7。", "安定の序列は Root→5th→3rd→7th（力強い→豊か）。"],
      staff: ["C4", "E4", "G4", "B4"], staffOpts: { brackets: [{ from: 0, to: 3, text: "R 3 5 7" }] }, keys: ["C4", "E4", "G4", "B4"] },
    { heading: "偶数シェルは解決を求める", key: "C",
      body: ["2・4・6度（D・F・A）はテンション。近くのコードトーンへ解決したがります。", "例：D→C、F→E、A→G。"],
      staff: ["D4", "C4", "F4", "E4", "A4", "G4"], keys: ["D4", "F4", "A4"] },
    { heading: "3度・6度のハモリ", key: "C",
      body: ["主メロに3度上（または下）を重ねると、やわらかい彩りのハモリになります。", "メロ C に上3度 E、下3度 A。3度と6度は転回関係の親戚です。"],
      staff: [{ chord: ["A3", "C4"], label: "下3度" }, { chord: ["C4", "E4"], label: "上3度" }], keys: ["A3", "C4", "E4"] },
    { heading: "声部進行：反行・斜行・並行", key: "C",
      body: ["2声の動きは3種類：逆向き（反行＝力強い）、片方だけ動く（斜行）、同じ向き（並行＝一体感）。", "下の例は外側の2声が開いていく反行です。"],
      staff: [["C4", "E4"], ["B3", "F4"]], keys: ["C4", "E4", "B4", "F4"] },
    { heading: "練習：Cコードのシェル", key: "C",
      body: ["Cコードに対する R・3・5・7（ド・ミ・ソ・シ）を弾いて響きの違いを感じましょう。"],
      practice: { notes: [0, 4, 7, 11], label: "シェル R-3-5-7" } },
    { heading: "練習：3度のハモリ", key: "C",
      body: ["メロディの各音に、上3度を重ねて弾いてみましょう（C+E, D+F, E+G, F+A, G+B）。", "スケールに沿って3度を平行に動かすと、やわらかい彩りのハモリになります。"],
      practice: { voicings: [[0, 4], [2, 5], [4, 7], [5, 9], [7, 11]], label: "3度ハモリ（上3度）" } },
  ] },

  { title: "Part 14 ダイアトニックコード①", chapter: "コード編", slides: [
    { heading: "コード＝3度の積み重ね", key: "C",
      body: ["コード（和音）は、1つおきの音を3つ重ねて作ります（三和音）。", "下から ルート（根音）・3度・5度。たとえば C は C・E・G です。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }], keys: ["C4", "E4", "G4"], listen: { notes: ["C4", "E4", "G4"], seq: false } },
    { heading: "メジャーとマイナー", key: "C",
      body: ["明るいメジャーは「長3度＋短3度」、暗いマイナーは「短3度＋長3度」。", "変わるのは真ん中の3度の音だけ。ここで明暗が決まります。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }, { chord: ["C4", "Eb4", "G4"], label: "Cm" }], keys: ["C4", "Eb4", "G4"] },
    { heading: "ダイアトニックトライアド", key: "C",
      body: ["スケールの各音の上に三和音を積むと、そのキーで使える7つのコードになります。", "Cメジャー：C・Dm・Em・F・G・Am・Bdim。"],
      staff: [ch("C", "maj", "C"), ch("D", "min", "Dm"), ch("E", "min", "Em"), ch("F", "maj", "F"), ch("G", "maj", "G"), ch("A", "min", "Am"), ch("B", "dim", "Bdim")],
      keys: ["C4", "D4", "E4", "F4", "G4", "A4", "B4"] },
    { heading: "度数（ローマ数字）", key: "C",
      body: ["コードを番号（ローマ数字）で呼ぶと、キーが変わっても同じ理屈で考えられます。", "大文字＝メジャー、小文字＝マイナー、°＝ディミニッシュ。"],
      staff: [ch("C", "maj", "I"), ch("F", "maj", "IV"), ch("G", "maj", "V")] },
    { heading: "練習：ダイアトニック（トライアド）", key: "C",
      body: ["Cメジャーの7つのコードを、順番に弾いてみましょう。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "D", type: "min" }, { root: "E", type: "min" }, { root: "F", type: "maj" }, { root: "G", type: "maj" }, { root: "A", type: "min" }, { root: "B", type: "dim" }], label: "ダイアトニックコード" } },
  ] },

  { title: "Part 15 ダイアトニックコード②", slides: [
    { heading: "4和音＝7thを足す", key: "C",
      body: ["三和音の上に、もう1つ3度を重ねると4和音（セブンスコード）になります。", "たとえば Cmaj7 は C・E・G・B。厚みのある響きになります。"],
      staff: [{ chord: ["C4", "E4", "G4", "B4"], label: "Cmaj7" }], keys: ["C4", "E4", "G4", "B4"], listen: { notes: ["C4", "E4", "G4", "B4"], seq: false } },
    { heading: "4種類の7th", key: "C",
      body: ["同じ7thでも4種類。maj7＝メジャー＋長7度、m7＝マイナー＋短7度。", "7（ドミナント7th）＝メジャー＋短7度、m7♭5＝ディミニッシュ＋短7度。"],
      staff: [ch("C", "maj7", "maj7"), ch("C", "min7", "m7"), ch("C", "dom7", "7"), ch("C", "m7b5", "m7♭5")] },
    { heading: "上手な数え方", key: "C",
      body: ["見分けるコツは2つ。①土台の三和音がメジャーかマイナーか。", "②7度がルートの半音下（長7）か、全音下（短7）か。この2点でわかります。"],
      staff: [ch("C", "maj7", "maj7=長7"), ch("C", "dom7", "7=短7")], keys: ["C4", "Bb4", "B4"] },
    { heading: "ダイアトニック7th", key: "C",
      body: ["Cメジャーの7th：Imaj7・IIm7・IIIm7・IVmaj7・V7・VIm7・VIIm7♭5。", "Vの位置だけがドミナント7th（G7）になります。"],
      staff: [ch("C", "maj7", "Cmaj7"), ch("D", "min7", "Dm7"), ch("E", "min7", "Em7"), ch("F", "maj7", "Fmaj7"), ch("G", "dom7", "G7"), ch("A", "min7", "Am7"), ch("B", "m7b5", "Bm7♭5")] },
    { heading: "練習：ダイアトニック7th", key: "C",
      body: ["Cメジャーの7つのセブンスコードを順に弾いてみましょう。"],
      practice: { chords: [{ root: "C", type: "maj7" }, { root: "D", type: "min7" }, { root: "E", type: "min7" }, { root: "F", type: "maj7" }, { root: "G", type: "dom7" }, { root: "A", type: "min7" }, { root: "B", type: "m7b5" }], label: "ダイアトニック7th" } },
  ] },

  { title: "Part 16 コード進行①", slides: [
    { heading: "進行の力＝ルートの動き", key: "C",
      body: ["コードの進み方で最も強いのは、ルートが4度上がる（＝5度下がる）動きです。", "たとえば C→F、G→C。次へ「進んだ」感じが強く出ます。"],
      staff: [ch("C", "maj", "C"), ch("F", "maj", "F")] },
    { heading: "基本のスリーコード",
      example: { tempo:120, chords:[{offs:[0,4,7],beats:2},{offs:[5,9,12],beats:2},{offs:[7,11,14],beats:2},{offs:[0,4,7],beats:2}], melody:[[4,1],[9,1],[11,1],[12,1],[7,1],[5,1],[4,1],[0,1]], label:"I-IV-V-I" }, key: "C",
      body: ["I・IV・V の3つは、コード進行の土台です。", "I-IV-V-I が、いちばん基本の流れになります。"],
      staff: [ch("C", "maj", "I"), ch("F", "maj", "IV"), ch("G", "maj", "V"), ch("C", "maj", "I")], keys: ["C4", "F4", "G4"] },
    { heading: "王道進行など",
      example: { tempo:120, chords:[{offs:[5,9,12],beats:2},{offs:[7,11,14],beats:2},{offs:[4,7,11],beats:2},{offs:[9,12,16],beats:2}], melody:[[9,1],[12,1],[11,1],[9,1],[7,1],[11,1],[9,2]], label:"王道進行 IV-V-iii-vi" }, key: "C",
      body: ["I-V-vi-IV（C-G-Am-F）は、ポップスで大人気の「王道進行」。", "ほかに I-vi-IV-V や ii-V-I もよく使われます。"],
      staff: [ch("C", "maj", "I"), ch("G", "maj", "V"), ch("A", "min", "vi"), ch("F", "maj", "IV")] },
    { heading: "カノン進行",
      example: { tempo:120, chords:[{offs:[0,4,7],beats:2},{offs:[7,11,14],beats:2},{offs:[9,12,16],beats:2},{offs:[4,7,11],beats:2},{offs:[5,9,12],beats:2},{offs:[0,4,7],beats:2},{offs:[5,9,12],beats:2},{offs:[7,11,14],beats:2}], melody:[[16,2],[14,2],[12,2],[11,2],[9,2],[7,2],[9,1],[11,1],[12,2]], label:"カノン進行" }, key: "C",
      body: ["I-V-vi-iii-IV-I-IV-V は「カノン進行」。", "ベースがなめらかに下がっていく、感動的な進行です。"],
      staff: [ch("C", "maj", "I"), ch("G", "maj", "V"), ch("A", "min", "vi"), ch("E", "min", "iii"), ch("F", "maj", "IV"), ch("C", "maj", "I"), ch("F", "maj", "IV"), ch("G", "maj", "V")] },
    { heading: "練習：I-IV-V-I", key: "C",
      body: ["いちばん基本の I-IV-V-I を弾いてみましょう。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "F", type: "maj" }, { root: "G", type: "maj" }, { root: "C", type: "maj" }], label: "I-IV-V-I" } },
    { heading: "練習：王道進行 I-V-vi-IV", key: "C",
      body: ["ポップスで大人気の王道進行 C-G-Am-F。明るさと切なさが同居する定番です。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "G", type: "maj" }, { root: "A", type: "min" }, { root: "F", type: "maj" }], label: "王道進行 I-V-vi-IV" } },
    { heading: "練習：カノン進行", key: "C",
      body: ["ベースがなめらかに下がるカノン進行 C-G-Am-Em-F-C-F-G を弾いてみましょう。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "G", type: "maj" }, { root: "A", type: "min" }, { root: "E", type: "min" }, { root: "F", type: "maj" }, { root: "C", type: "maj" }, { root: "F", type: "maj" }, { root: "G", type: "maj" }], label: "カノン進行" } },
  ] },

  { title: "Part 17 転回形の基本", slides: [
    { heading: "転回形とは", key: "C",
      body: ["コードは、構成音を積む順番を変えても同じコードです。これを「転回形」といいます。", "変わるのは、いちばん下の音（ベース）だけです。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }], keys: ["C4", "E4", "G4"] },
    { heading: "三和音の3通り", key: "C",
      body: ["三和音には3通りの積み方があります。基本形（ルートが最低音）。", "第1転回形（3度が最低音）、第2転回形（5度が最低音）。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "基本形" }, { chord: ["E4", "G4", "C5"], label: "第1転回" }, { chord: ["G4", "C5", "E5"], label: "第2転回" }], voicing: [4, 7, 12] },
    { heading: "分数（スラッシュ）表記", key: "C",
      body: ["転回形は「コード名／ベース音」の形で書きます。", "Cの第1転回形は C/E、第2転回形は C/G です。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }, { chord: ["E4", "G4", "C5"], label: "C/E" }, { chord: ["G4", "C5", "E5"], label: "C/G" }] },
    { heading: "練習：Cの転回形", key: "C",
      body: ["基本形→第1転回→第2転回の順に、光った鍵盤（最低音）に注意して弾こう。"],
      practice: { voicings: [[0, 4, 7], [4, 7, 12], [7, 12, 16]], label: "Cの転回形" } },
  ] },

  { title: "Part 18 転回形の利用", slides: [
    { heading: "目的はベースの滑らかさ", key: "C",
      body: ["転回形を使う目的は、ベースの動きをなめらかにすること（ボイスリーディング）。", "音の移動が少なくなり、上品で自然な進行になります。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }, { chord: ["B3", "D4", "G4"], label: "G/B" }, { chord: ["A3", "C4", "E4"], label: "Am" }] },
    { heading: "下降ベースの例", key: "C",
      body: ["C→G/B→Am→C/G→F は、ベースが C-B-A-G… となめらかに下がります。", "カノン進行などでよく使う、定番の形です。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }, { chord: ["B3", "D4", "G4"], label: "G/B" }, { chord: ["A3", "C4", "E4"], label: "Am" }, { chord: ["G3", "C4", "E4"], label: "C/G" }, { chord: ["F3", "A3", "C4"], label: "F" }] },
    { heading: "上行ベースの例", key: "C",
      body: ["C→C/E→F のように、転回形でベースを上げていくこともできます。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }, { chord: ["E4", "G4", "C5"], label: "C/E" }, { chord: ["F4", "A4", "C5"], label: "F" }] },
    { heading: "練習：C → G/B → Am → C/G → F（下行）", key: "C",
      body: ["ベースがなめらかに下がる動き（C-B-A-G-F）を感じながら弾いてみましょう。"],
      practice: { voicings: [[0, 4, 7], [11, 14, 19], [9, 12, 16], [7, 12, 16], [5, 9, 12]], label: "転回形でつなぐ（下行）" } },
    { heading: "練習：C → C/E → F（上行）", key: "C",
      body: ["今度はベースを上げる転回形。C-E-F と、最低音が上がっていく流れを弾いてみましょう。"],
      practice: { voicings: [[0, 4, 7], [4, 7, 12], [5, 9, 12]], label: "転回形でつなぐ（上行）" } },
  ] },

  { title: "Part 19 コードの機能と代理コード①", slides: [
    { heading: "3つの機能", key: "C",
      body: ["コードには3つの役割（機能）があります。トニック(T)＝安定、サブドミナント(SD)＝展開、ドミナント(D)＝緊張。", "D→T と進むと「解決」した感じになります。"],
      staff: [ch("C", "maj", "T"), ch("F", "maj", "SD"), ch("G", "maj", "D")] },
    { heading: "機能ごとのコード", key: "C",
      body: ["同じ機能を持つコードがあります。トニック：I・IIIm・VIm。", "サブドミナント：IV・IIm。 ドミナント：V・VIIdim。"],
      staff: [ch("C", "maj", "I"), ch("E", "min", "IIIm"), ch("A", "min", "VIm")] },
    { heading: "ケーデンス（終止）", key: "C",
      body: ["フレーズの終わり方を「ケーデンス（終止）」といいます。", "完全終止 V→I、変終止 IV→I、半終止 →V、偽終止 V→VIm。"],
      staff: [ch("G", "maj", "V"), ch("C", "maj", "I")] },
    { heading: "練習：ii-V-I", key: "C",
      body: ["サブドミナント→ドミナント→トニックの ii-V-I を弾いてみましょう。"],
      practice: { chords: [{ root: "D", type: "min" }, { root: "G", type: "maj" }, { root: "C", type: "maj" }], label: "ii-V-I" } },
    { heading: "練習：完全終止 V→I", key: "C",
      body: ["G→C。ドミナントからトニックへ、いちばん強く「終わった」と感じる終止です。"],
      practice: { chords: [{ root: "G", type: "maj" }, { root: "C", type: "maj" }], label: "完全終止 V→I" } },
    { heading: "練習：変終止 IV→I", key: "C",
      body: ["F→C。サブドミナントから解決する、やわらかい「アーメン終止」です。"],
      practice: { chords: [{ root: "F", type: "maj" }, { root: "C", type: "maj" }], label: "変終止 IV→I" } },
    { heading: "練習：半終止 I→V", key: "C",
      body: ["C→G。あえてドミナントで止め、「続きがある」宙づり感を残す終止です。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "G", type: "maj" }], label: "半終止 →V" } },
    { heading: "練習：偽終止 V→VIm", key: "C",
      body: ["G→Am。I へ解決すると思わせて VIm へ。意外性のある「はぐらかし」の終止です。"],
      practice: { chords: [{ root: "G", type: "maj" }, { root: "A", type: "min" }], label: "偽終止 V→VIm" } },
  ] },

  { title: "Part 20 コードの機能と代理コード②", slides: [
    { heading: "代理コードとは", key: "C",
      body: ["あるコードを、同じ機能の別のコードに置きかえることを「代理」といいます。", "共通する音が多いほど、自然に置きかえられます。"],
      staff: [ch("C", "maj", "C (I)"), ch("A", "min", "Am (VIm)")], keys: ["C4", "E4", "G4", "A4"] },
    { heading: "代表的な代理", key: "C",
      body: ["トニック同士 I⇄IIIm⇄VIm。サブドミナント同士 IV⇄IIm。", "ドミナント同士 V⇄VIIdim。"],
      staff: [ch("C", "maj", "I"), ch("E", "min", "IIIm"), ch("A", "min", "VIm")] },
    { heading: "注意点", key: "C",
      body: ["IIImは中間的な性格で、代理が弱くなる場面もあります。", "V→VIm（偽終止）は、あえて解決を外して意外性を出す使い方です。"],
      staff: [ch("G", "maj", "V"), ch("A", "min", "VIm（偽終止）")] },
    { heading: "練習：I-IIm-V-VIm", key: "C",
      body: ["代理コードを使った I-IIm-V-VIm を弾いてみましょう。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "D", type: "min" }, { root: "G", type: "maj" }, { root: "A", type: "min" }], label: "代理を使った進行" } },
    { heading: "練習：トニック代理 I-IIIm-VIm", key: "C",
      body: ["同じトニック機能の C→Em→Am を弾き比べ。共通音が多く、なめらかに置きかわります。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "E", type: "min" }, { root: "A", type: "min" }], label: "トニック代理（I-IIIm-VIm）" } },
    { heading: "練習：サブドミナント代理 IV⇄IIm", key: "C",
      body: ["同じサブドミナント機能の F と Dm。F→Dm→G→C と、IV を IIm に置きかえた進行を弾いてみましょう。"],
      practice: { chords: [{ root: "F", type: "maj" }, { root: "D", type: "min" }, { root: "G", type: "maj" }, { root: "C", type: "maj" }], label: "SD代理（IV⇄IIm）" } },
  ] },

  { title: "Part 21 ドミナントモーション", slides: [
    { heading: "V7→I が最強の解決", key: "C",
      body: ["V7→I は、もっとも強く「解決」を感じるコードの動きです。", "ルートが4度上がり、さらに緊張した音（トライトーン）がほどけます。"],
      staff: [ch("G", "dom7", "V7"), ch("C", "maj", "I")] },
    { heading: "トライトーンの解決", key: "C",
      body: ["G7 にふくまれる「シ」と「ファ」が、次の C の「ド」「ミ」へ吸い込まれます。", "この動きが、強い解決感を生みます。"],
      staff: [{ chord: ["G3", "B3", "D4", "F4"], label: "G7" }, { chord: ["C4", "E4", "G4"], label: "C" }],
      keys: ["G3", "B3", "D4", "F4"], listen: { notes: ["G3", "B3", "D4", "F4"], seq: false } },
    { heading: "なぜ強いか", key: "C",
      body: ["「シ」と「ファ」は不安定な音程（トライトーン）です。", "これが安定した音へ動くことが、あらゆる解決の核になっています。"],
      staff: [{ chord: ["B3", "F4"], label: "シ・ファ" }], keys: ["B3", "F4"] },
    { heading: "練習：G7 → C", key: "C",
      body: ["いちばん強い解決 G7→C を弾いてみましょう。"],
      practice: { chords: [{ root: "G", type: "dom7" }, { root: "C", type: "maj" }], label: "ドミナントモーション" } },
    { heading: "練習：トライトーンの解決", key: "C",
      body: ["G7 の核＝ファ＋シ（トライトーン）だけを弾き、次に ミ＋ド へ。2音が半音で解決する瞬間を体感しましょう。"],
      practice: { voicings: [[5, 11], [4, 12]], label: "トライトーン解決（ファ・シ→ミ・ド）" } },
  ] },

  { title: "Part 22 マイナースケールのドミナント", slides: [
    { heading: "自然短調の問題", key: "A",
      body: ["ナチュラルマイナーだと、Vのコードがマイナー(Vm)になります。", "導音（主音の半音下の音）が無いため、ドミナントの緊張感が弱くなります。"],
      staff: [{ chord: ["E4", "G4", "B4"], label: "Em (Vm・弱い)" }], keys: ["E4", "G4", "B4"] },
    { heading: "ハーモニックマイナー", key: "A",
      body: ["そこで第7音を半音上げ、導音を作ります（Aマイナーなら G→G♯）。", "すると V が V7（E7）になり、強い解決が使えるようになります。"],
      staff: ["A3", "B3", "C4", "D4", "E4", "F4", "G#4", "A4"], keys: ["A3", "B3", "C4", "D4", "E4", "F4", "G#4"] },
    { heading: "メロディックマイナー", key: "A",
      body: ["ハーモニックマイナーは6→7度が広くて歌いにくいので、上行では6度も上げます。", "これがメロディックマイナー。下行では元に戻すのが古典的です。"],
      staff: ["A3", "B3", "C4", "D4", "E4", "F#4", "G#4", "A4"], keys: ["A3", "B3", "C4", "D4", "E4", "F#4", "G#4"] },
    { heading: "練習：Aハーモニックマイナー", key: "A",
      body: ["第7音を上げたハーモニックマイナーの並びで弾いてみましょう。"],
      practice: { notes: HMIN, label: "ハーモニックマイナー" } },
    { heading: "練習：Aメロディックマイナー（上行）", key: "A",
      body: ["歌いやすいよう第6音も上げた上行形（A B C D E F♯ G♯ A）。増2度が消えてなめらかです。"],
      practice: { notes: [0, 2, 3, 5, 7, 9, 11, 12], label: "メロディックマイナー（上行）" } },
    { heading: "練習：E7 → Am（マイナーの解決）", key: "C",
      body: ["導音 G♯ を持つ E7 から Am へ。マイナーキーでも強いドミナント解決が使えます。"],
      practice: { chords: [{ root: "E", type: "dom7" }, { root: "A", type: "min" }], label: "V7→Im（E7→Am）" } },
  ] },

  { title: "Part 23 セカンダリドミナント", slides: [
    { heading: "考え方", key: "C",
      body: ["キーの中のあるコードを、一時的に「そのキーの I」とみなします。", "そのIへ向かう V7 を借りてくるのが「セカンダリドミナント」（V7/x）です。"],
      staff: [ch("C", "maj", "C"), ch("E", "dom7", "E7 (V7/VI)")] },
    { heading: "作れる対象（5つすべて）", key: "C",
      body: ["dim 以外の各ダイアトニックコードへ、それぞれ V7 を作れます。V7/II〜V7/VI の5つです。", "A7→Dm・B7→Em・C7→F・D7→G・E7→Am。どれも「向かう先の半音下に導音」ができています。"],
      staff: [ch("A", "dom7", "V7/II"), ch("D", "min", "IIm"), ch("B", "dom7", "V7/III"), ch("E", "min", "IIIm"), ch("C", "dom7", "V7/IV"), ch("F", "maj", "IV"), ch("D", "dom7", "V7/V"), ch("G", "maj", "V"), ch("E", "dom7", "V7/VI"), ch("A", "min", "VIm")] },
    { heading: "使い方", key: "C",
      body: ["向かいたいコードの直前に置くと、そのコードが強調され、色づきます。"],
      staff: [ch("C", "maj", "C"), ch("E", "dom7", "E7"), ch("A", "min", "Am")] },
    { heading: "練習：C → E7 → Am（V7/VI）", key: "C",
      body: ["C→E7→Am。E7 が次の Am を引き立てます。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "E", type: "dom7" }, { root: "A", type: "min" }], label: "セカンダリドミナント V7/VI" } },
    { heading: "練習：C → D7 → G（V7/V）", key: "C",
      body: ["別の対象も。C→D7→G。D7（＝V7/V）が、ドミナントの G を強調します。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "D", type: "dom7" }, { root: "G", type: "maj" }], label: "セカンダリドミナント V7/V" } },
    { heading: "練習：C → A7 → Dm（V7/II）", key: "C",
      body: ["A7（＝V7/II）で Dm を引き立てる形。マイナーへ向かうセカンダリドミナントも弾いてみましょう。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "A", type: "dom7" }, { root: "D", type: "min" }], label: "セカンダリドミナント V7/II" } },
  ] },

  { title: "Part 24 ツーファイブワン", slides: [
    { heading: "ii-V-I の基本",
      example: { tempo:132, chords:[{offs:[2,5,9,12],beats:4},{offs:[7,11,14,17],beats:4},{offs:[0,4,7,11],beats:4}], melody:[[9,1],[12,1],[5,2],[11,1],[14,1],[17,1],[11,1],[4,2],[7,2]], label:"ii-V-I（ガイドトーン）" }, key: "C",
      body: ["サブドミナント(ii)→ドミナント(V)→トニック(I) の流れが ii-V-I。", "Dm7-G7-Cmaj7。ジャズで最もよく使う進行です。"],
      staff: [ch("D", "min7", "IIm7"), ch("G", "dom7", "V7"), ch("C", "maj7", "Imaj7")] },
    { heading: "リレイテッドⅡm7", key: "C",
      body: ["セカンダリドミナントの前に、その完全5度上のマイナー7thを足せます。", "例：E7 の前に Bm7 を置くと、Bm7-E7-Am というミニ ii-V になります。"],
      staff: [ch("B", "min7", "Bm7"), ch("E", "dom7", "E7"), ch("A", "min", "Am")] },
    { heading: "マイナーなら IIm7♭5", key: "C",
      body: ["向かう先がマイナーコードのときは、IIを m7♭5 にします。", "例：Am へ向かうなら Bm7♭5-E7-Am。"],
      staff: [ch("B", "m7b5", "Bm7♭5"), ch("E", "dom7", "E7"), ch("A", "min", "Am")] },
    { heading: "練習：Dm7-G7-Cmaj7（メジャー）", key: "C",
      body: ["ジャズの基本 Dm7-G7-Cmaj7 を弾いてみましょう。"],
      practice: { chords: [{ root: "D", type: "min7" }, { root: "G", type: "dom7" }, { root: "C", type: "maj7" }], label: "ii-V-I（メジャー）" } },
    { heading: "練習：Bm7♭5-E7-Am（マイナー）", key: "C",
      body: ["向かう先がマイナーのときは II を m7♭5 に。Bm7♭5-E7-Am のマイナー ii-V-i を弾いてみましょう。"],
      practice: { chords: [{ root: "B", type: "m7b5" }, { root: "E", type: "dom7" }, { root: "A", type: "min" }], label: "ii-V-i（マイナー）" } },
    { heading: "練習：リレイテッドⅡ（Bm7-E7-Am）", key: "C",
      body: ["セカンダリドミナント E7 の前に Bm7 を足したミニ ii-V。Bm7-E7-Am となめらかにつなぎます。"],
      practice: { chords: [{ root: "B", type: "min7" }, { root: "E", type: "dom7" }, { root: "A", type: "min" }], label: "リレイテッドⅡm7" } },
  ] },

  { title: "Part 25 コード進行②", slides: [
    { heading: "実例①", key: "C",
      body: ["C - A7 - Dm - G7 - C。", "A7（＝V7/II）が、次の Dm を引き立てています。"],
      staff: [ch("C", "maj", "C"), ch("A", "dom7", "A7"), ch("D", "min", "Dm"), ch("G", "dom7", "G7"), ch("C", "maj", "C")] },
    { heading: "実例②（リレイテッドⅡ）", key: "C",
      body: ["C - Em7 - A7 - Dm7 - G7 - C。", "Em7-A7 のミニ ii-V が、Dm7 へなめらかにつなぎます。"],
      staff: [ch("C", "maj", "C"), ch("E", "min7", "Em7"), ch("A", "dom7", "A7"), ch("D", "min7", "Dm7"), ch("G", "dom7", "G7"), ch("C", "maj", "C")] },
    { heading: "ツーファイブの連続", key: "C",
      body: ["ii-V をくり返しながら下がっていく、ジャズの定番パターンです。"],
      staff: [ch("E", "min7", "Em7"), ch("A", "dom7", "A7"), ch("D", "min7", "Dm7"), ch("G", "dom7", "G7")] },
    { heading: "練習：C-A7-Dm7-G7-C（実例①）", key: "C",
      body: ["セカンダリドミナント A7 を使った進行を弾いてみましょう。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "A", type: "dom7" }, { root: "D", type: "min7" }, { root: "G", type: "dom7" }, { root: "C", type: "maj" }], label: "実例①（V7/II）" } },
    { heading: "練習：C-Em7-A7-Dm7-G7-C（実例②）", key: "C",
      body: ["Em7-A7 のミニ ii-V を挟んだ実例②。Dm7 へよりなめらかにつながります。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "E", type: "min7" }, { root: "A", type: "dom7" }, { root: "D", type: "min7" }, { root: "G", type: "dom7" }, { root: "C", type: "maj" }], label: "実例②（リレイテッドⅡ）" } },
  ] },

  { title: "Part 26 パッシングディミニッシュ", slides: [
    { heading: "パッシングディミニッシュとは", key: "C",
      body: ["全音はなれた2つのコードの間に、半音上のディミニッシュを挟むテクニックです。", "ベースが半音でつながり、なめらかな流れになります。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }, { chord: ["C#4", "E4", "G4"], label: "C♯dim" }, { chord: ["D4", "F4", "A4", "C5"], label: "Dm7" }] },
    { heading: "上行型（定番）", key: "C",
      body: ["I-♯Idim-IIm、IV-♯IVdim-V などが定番。", "例：C-C♯dim-Dm7。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }, { chord: ["C#4", "E4", "G4"], label: "C♯dim" }, { chord: ["D4", "F4", "A4", "C5"], label: "Dm7" }],
      keys: ["C#4", "E4", "G4"] },
    { heading: "仕組み", key: "C",
      body: ["dim にふくまれる緊張音が、次のコードの音へ解決します（C♯→D、G→F）。", "下がっていく形もありますが、上がる形がよく使われます。"],
      staff: [{ chord: ["C#4", "G4"], label: "C♯・ソ" }], keys: ["C#4", "G4"] },
    { heading: "練習：C → C♯dim → Dm7（I-♯Idim-IIm）", key: "C",
      body: ["半音でつなぐ C→C♯dim→Dm7 を弾いてみましょう。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "C#", type: "dim" }, { root: "D", type: "min7" }], label: "パッシングディミニッシュ（I-♯Idim-IIm）" } },
    { heading: "練習：F → F♯dim → G（IV-♯IVdim-V）", key: "C",
      body: ["もう一つの定番。F→F♯dim→G と、ベースが半音で上がりながら V へ向かいます。"],
      practice: { chords: [{ root: "F", type: "maj" }, { root: "F#", type: "dim" }, { root: "G", type: "maj" }], label: "パッシングディミニッシュ（IV-♯IVdim-V）" } },
  ] },

  { title: "Part 27 五度圏の利用", slides: [
    { heading: "五度圏とは", key: "C",
      body: ["調やコードを、完全5度ずつ円に並べたのが「五度圏」です。", "時計回りに進むと♯が1つずつ増え、反時計回りに進むと♭が増えます。"],
      staff: [ch("C", "maj", "C"), ch("G", "maj", "G"), ch("D", "maj", "D"), ch("A", "maj", "A")] },
    { heading: "調号の整理", key: "G",
      body: ["C(♯♭なし)→G(♯1)→D(♯2)→A(♯3)…と、5度ごとに調号が1つずつ増えます。", "Gメジャーは♯が1つ（F♯）だけの調です。"],
      staff: ["G4", "A4", "B4", "C5", "D5", "E5", "F#5", "G5"], keys: ["G3", "A3", "B3", "C4", "D4", "E4", "F#4"] },
    { heading: "ii-V-I も五度圏で動く", key: "C",
      body: ["ii-V-I は、ルートが反時計回り（4度上がる方向）に進みます。", "五度圏を見ると、ツーファイブの連続がひと目でわかります。"],
      staff: [ch("D", "min7", "Dm7"), ch("G", "dom7", "G7"), ch("C", "maj7", "Cmaj7")] },
    { heading: "練習：五度圏を右回り（トニック巡り）", key: "C",
      body: ["五度圏を時計回りに、各調のトニックを巡ってみましょう（C→G→D→A→E）。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "G", type: "maj" }, { root: "D", type: "maj" }, { root: "A", type: "maj" }, { root: "E", type: "maj" }], label: "五度圏（右回り）" } },
    { heading: "練習：五度圏を左回り（ii-V-I）", key: "C",
      body: ["ルートが4度上がる（反時計回り）動き＝ii-V-I。Dm7-G7-Cmaj7 が五度圏を左へ進むのを感じましょう。"],
      practice: { chords: [{ root: "D", type: "min7" }, { root: "G", type: "dom7" }, { root: "C", type: "maj7" }], label: "五度圏（左回り＝ii-V-I）" } },
  ] },

  { title: "Part 28 裏コード①", slides: [
    { heading: "裏コード＝トライトーン代理",
      example: { tempo:120, chords:[{offs:[2,5,9,12],beats:2},{offs:[1,5,8,11],beats:2},{offs:[0,4,7,11],beats:4}], melody:[[9,1],[12,1],[11,2],[8,1],[11,1],[12,2]], label:"裏コード Dm7-D♭7-C" }, key: "C",
      body: ["V7 を、共通のトライトーンを持つ「♭II7」に置きかえるのが「裏コード」です。", "G7→C なら、G7 の代わりに D♭7 を使えます。"],
      staff: [{ chord: ["G3", "B3", "D4", "F4"], label: "G7" }, { chord: ["Db4", "F4", "Ab4", "Cb5"], label: "D♭7" }],
      keys: ["Db4", "F4", "Ab4", "B4"] },
    { heading: "共有トライトーン", key: "C",
      body: ["G7 の「シ・ファ」と D♭7 の「ファ・ド♭(=シ)」は、まったく同じ2音です。", "この共通音があるから、置きかえても解決感が保たれます。"],
      staff: [{ chord: ["B3", "F4"], label: "シ・ファ" }], keys: ["B3", "F4"] },
    { heading: "効果", key: "C",
      body: ["ベースが D♭→C と半音で下がり、おしゃれでなめらかな響きになります。"],
      staff: [ch("D", "min7", "Dm7"), { chord: ["Db4", "F4", "Ab4", "Cb5"], label: "D♭7" }, ch("C", "maj", "C")] },
    { heading: "練習：Dm7 → D♭7 → C", key: "C",
      body: ["半音で下がる裏コードを弾いてみましょう（D♭7 は C♯7 と同じ音）。"],
      practice: { chords: [{ root: "D", type: "min7" }, { root: "C#", type: "dom7" }, { root: "C", type: "maj" }], label: "裏コード" } },
    { heading: "練習：表と裏を弾き比べ", key: "C",
      body: ["同じ C へ、G7（表）→C と D♭7（裏）→C。ベースの動き（5度下降／半音下降）の違いを聴き比べましょう。"],
      practice: { chords: [{ root: "G", type: "dom7" }, { root: "C", type: "maj" }, { root: "C#", type: "dom7" }, { root: "C", type: "maj" }], label: "表(G7)と裏(D♭7)" } },
  ] },

  { title: "Part 29 サブドミナント終止とサブドミナントマイナー", slides: [
    { heading: "サブドミナント終止（変終止）", key: "C",
      body: ["IV→I で終わる終止を「変終止（プラガル）」といいます。", "「アーメン終止」とも呼ばれ、やわらかく落ち着く響きです。"],
      staff: [ch("F", "maj", "IV"), ch("C", "maj", "I")] },
    { heading: "サブドミナントマイナー(SDM)", key: "C",
      body: ["同主短調（Cマイナー）から借りるサブドミナントが「サブドミナントマイナー」。", "代表は IVm。IV→IVm→I とすると、切ない終止感が出ます。"],
      staff: [ch("F", "maj", "IV"), ch("F", "min", "IVm"), ch("C", "maj", "I")], keys: ["F4", "Ab4", "C5"] },
    { heading: "SDMの仲間", key: "C",
      body: ["ほかに ♭VI・♭VII・IIm♭5 などがあります。", "♭VI→♭VII→I は、余韻の残るサビ終わりの定番です。"],
      staff: [{ chord: ["Ab3", "C4", "Eb4"], label: "♭VI" }, { chord: ["Bb3", "D4", "F4"], label: "♭VII" }, { chord: ["C4", "E4", "G4"], label: "I" }] },
    { heading: "練習：F → C（変終止）", key: "C",
      body: ["まずは基本の IV→I。やわらかく落ち着く「アーメン終止」を弾いてみましょう。"],
      practice: { chords: [{ root: "F", type: "maj" }, { root: "C", type: "maj" }], label: "変終止 IV→I" } },
    { heading: "練習：F → Fm → C（SDM）", key: "C",
      body: ["F→Fm→C。同主短調から借りた IVm の、切ない響きを味わいましょう。"],
      practice: { chords: [{ root: "F", type: "maj" }, { root: "F", type: "min" }, { root: "C", type: "maj" }], label: "サブドミナントマイナー" } },
    { heading: "練習：♭VI → ♭VII → I", key: "C",
      body: ["A♭→B♭→C。同主短調から借りた ♭VI・♭VII で、余韻の残るサビ終わりの定番進行です。"],
      practice: { chords: [{ root: "G#", type: "maj" }, { root: "A#", type: "maj" }, { root: "C", type: "maj" }], label: "♭VI-♭VII-I" } },
  ] },

  { title: "Part 30 クリシェとペダルポイント", slides: [
    { heading: "クリシェ", key: "C",
      body: ["コードはほぼ保ったまま、内側の音を半音ずつ動かすラインが「クリシェ」です。", "例：Cm-CmM7-Cm7-Cm6（中で C-B-B♭-A と下がる線が動く）。"],
      staff: [ch("C", "min", "Cm"), ch("C", "mM7", "CmM7"), ch("C", "min7", "Cm7"), ch("C", "m6", "Cm6")] },
    { heading: "ペダルポイント", key: "C",
      body: ["ベース（や特定の音）を鳴らし続けたまま、上のコードだけを動かす手法です。", "主音を保つトニックペダル、属音を保つドミナントペダルが定番です。"],
      staff: [{ chord: ["C4", "E4", "G4"], label: "C" }, { chord: ["C4", "G4", "B4", "D5"], label: "G/C" }, { chord: ["C4", "F4", "A4"], label: "F/C" }] },
    { heading: "効果", key: "C",
      body: ["動きの中に「変わらない軸」ができ、統一感や緊張の持続が生まれます。", "（上の楽譜は、クリシェの動く線 C-B-B♭-A）"],
      staff: [{ name: "C5", label: "C" }, { name: "B4", label: "B" }, { name: "Bb4", label: "B♭" }, { name: "A4", label: "A" }], keys: ["C5", "B4", "Bb4", "A4"] },
    { heading: "練習：Cm クリシェ（マイナー）", key: "C",
      body: ["内声が半音で下がる Cm のクリシェを弾いてみましょう（C-B-B♭-A の線が動く）。"],
      practice: { chords: [{ root: "C", type: "min" }, { root: "C", type: "mM7" }, { root: "C", type: "min7" }, { root: "C", type: "m6" }], label: "クリシェ（マイナー）" } },
    { heading: "練習：C クリシェ（メジャー）", key: "C",
      body: ["メジャーでも同じ手法。C→Cmaj7→C7→C6 と、上の線が B→B♭→A と半音で下がります。"],
      practice: { chords: [{ root: "C", type: "maj" }, { root: "C", type: "maj7" }, { root: "C", type: "dom7" }, { root: "C", type: "six" }], label: "クリシェ（メジャー）" } },
  ] },

  { title: "Part 31 sus4系分数コード", slides: [
    { heading: "sus4 の復習", key: "C",
      body: ["sus4 は、3度の代わりに完全4度を使うコード。宙づりのような響きです。", "Gsus4→G のように、3度へ動いて解決したくなります。"],
      staff: [{ chord: ["G3", "C4", "D4"], label: "Gsus4" }, { chord: ["G3", "B3", "D4"], label: "G" }], keys: ["G4", "C5", "D5"] },
    { heading: "sus4系分数コード", key: "C",
      body: ["ベース音の上に別の和音を重ねて、sus4 のような響きを作る分数コードです。", "例：Dm7/G、F/G、C/D。"],
      staff: [{ chord: ["G3", "D4", "F4", "A4", "C5"], label: "Dm7/G" }, { chord: ["G3", "F4", "A4", "C5"], label: "F/G" }] },
    { heading: "使い方", key: "C",
      body: ["V の手前や V の代わりに置くと、やわらかいドミナントの響きになります。"],
      staff: [{ chord: ["G3", "D4", "F4", "A4", "C5"], label: "Dm7/G" }, { chord: ["C4", "E4", "G4"], label: "C" }] },
    { heading: "練習：Gsus4 → C", key: "C",
      body: ["sus4 の宙づり感から、C へ解決する流れを弾いてみましょう。"],
      practice: { chords: [{ root: "G", type: "sus4" }, { root: "C", type: "maj" }], label: "sus4分数（近似）" } },
    { heading: "練習：F/G → C（sus4系分数）", key: "G",
      body: ["G の上に F の三和音を重ねた F/G（G・F・A・C）。やわらかいドミナントとして C へ解決します。"],
      practice: { voicings: [[0, 10, 14, 17], [5, 9, 12]], label: "F/G → C" } },
  ] },

  { title: "Part 32 add9と9thコード", slides: [
    { heading: "テンションとは", key: "C",
      body: ["コードの土台の音(1,3,5,7)の上に重ねる、色づけの音が「テンション」です。", "オクターブ＋2・4・6度＝9th・11th・13th。"],
      staff: [{ chord: ["C4", "E4", "G4", "D5", "F5", "A5"], label: "9・11・13" }], keys: ["D5", "F5", "A5"] },
    { heading: "add9", key: "C",
      body: ["三和音に9thだけを足したコード（7thは入れません）。", "Cadd9＝C・E・G・D。明るく広がる響きです。"],
      staff: [{ chord: ["C4", "E4", "G4", "D5"], label: "Cadd9" }], keys: ["C4", "E4", "G4", "D5"] },
    { heading: "9thコード", key: "C",
      body: ["セブンスコードに、さらに9thを重ねたのが9thコードです。", "Cmaj9・C9・Cm9 など。おしゃれで厚みのある響きになります。"],
      staff: [{ chord: ["C4", "E4", "G4", "B4", "D5"], label: "Cmaj9" }], keys: ["C4", "E4", "G4", "B4", "D5"], listen: { notes: ["C4", "E4", "G4", "B4", "D5"], seq: false } },
    { heading: "練習：Cadd9", key: "C",
      body: ["Cadd9（C・E・G・D）の、きらびやかな響きを弾いてみましょう（7thは入れません）。"],
      practice: { chords: [{ root: "C", type: "add9" }], label: "add9" } },
    { heading: "練習：Cmaj9", key: "C",
      body: ["Cmaj7 に9thを足した Cmaj9（C・E・G・B・D）。おしゃれで厚みのある響きです。"],
      practice: { voicings: [[0, 4, 7, 11, 14]], label: "Cmaj9" } },
    { heading: "練習：C9（ドミナント9th）", key: "C",
      body: ["C7 に9thを足した C9（C・E・G・B♭・D）。ファンキーで前へ進む響きです。"],
      practice: { voicings: [[0, 4, 7, 10, 14]], label: "C9" } },
  ] },

  { title: "Part 33 11thコードと13thコード", slides: [
    { heading: "11thと13th", key: "C",
      body: ["テンションはさらに上に積めます。11th＝4度上、13th＝6度上の音です。"],
      staff: [{ chord: ["C4", "E4", "G4", "Bb4", "F5", "A5"], label: "C 11・13" }], keys: ["F5", "A5"] },
    { heading: "アヴォイドノート", key: "C",
      body: ["コードの音と半音でぶつかり、濁って聞こえる音を「アヴォイドノート」といいます。", "メジャー系の11thは3度とぶつかるため、そのままでは使いません。"],
      staff: [{ chord: ["C4", "E4", "F4"], label: "3度と11度が衝突" }], keys: ["E4", "F4"] },
    { heading: "対処", key: "C",
      body: ["11th は ♯11 に変えるか、sus4 にして3度を抜くと使えます。", "13th は上のほうに置くと、きれいに響きます。"],
      staff: [{ chord: ["C4", "E4", "G4", "F#5"], label: "C(♯11)" }], keys: ["C4", "E4", "G4", "F#5"] },
    { heading: "練習：C7sus4（3度を抜いて回避）", key: "C",
      body: ["対処その1。3度を抜いた sus4 で、11度（完全4度）の響きを活かしてみましょう。"],
      practice: { chords: [{ root: "C", type: "sus4" }], label: "sus4で11thを活かす" } },
    { heading: "練習：Cmaj7(♯11)（♯11で回避）", key: "C",
      body: ["対処その2。11thを半音上げた♯11(F♯) なら3度とぶつからず、明るく浮遊する響きになります。"],
      practice: { voicings: [[0, 4, 7, 11, 18]], label: "Cmaj7(♯11)" } },
  ] },

  { title: "Part 34 様々なテンションのテクニック", slides: [
    { heading: "アヴェイラブルテンション", key: "C",
      body: ["コード（の機能）ごとに、使えるテンションと避けるテンションが決まっています。", "例：Imaj7 では 9th・13th が使え、11th は避けます。"],
      staff: [{ chord: ["C4", "E4", "G4", "B4", "D5", "A5"], label: "Cmaj7(9,13)" }], keys: ["D5", "A5"] },
    { heading: "回避テク", key: "C",
      body: ["アヴォイドを避けるコツ：3度を抜く(sus)、♯11・♯9 に変える、上のほうに置く。"],
      staff: [{ chord: ["C4", "F4", "G4", "Bb4"], label: "C7sus4" }], keys: ["C4", "F4", "G4", "Bb4"] },
    { heading: "コード別の目安", key: "C",
      body: ["Imaj7：9,13。IIm7：9,11,13。", "V7：9,13＋オルタード。IVmaj7：9,♯11,13。"],
      staff: [{ chord: ["C4", "E4", "G4", "B4", "D5", "A5"], label: "Cmaj7(9,13)" }] },
    { heading: "練習：Cmaj9（9thの響き）", key: "C",
      body: ["C E G B D を弾いて、9th の広い響きを確かめましょう。"],
      practice: { voicings: [[0, 4, 7, 11, 14]], label: "maj9" } },
    { heading: "練習：C6/9（9と13）", key: "C",
      body: ["Imaj7 で使える 9th(D) と 13th(A=6) を同時に足した C6/9（C E G A D）。明るく広がる定番テンションです。"],
      practice: { voicings: [[0, 4, 7, 9, 14]], label: "C6/9（9,13）" } },
  ] },

  { title: "Part 35 オルタードテンションの基本", slides: [
    { heading: "オルタードテンションとは", key: "C",
      body: ["ドミナント7thにつく、変化したテンションを「オルタードテンション」といいます。", "♭9・♯9・♯11・♭13 の4つです。"],
      staff: [{ chord: ["G3", "B3", "F4", "Ab4", "Bb4", "Db5", "Eb5"], label: "G7alt" }], keys: ["Ab4", "Bb4", "Db5", "Eb5"] },
    { heading: "位置の確認", key: "C",
      body: ["ルートから見て ♭9(半音上)・♯9・♯11(＝減5度)・♭13(＝増5度) の位置にあります。"],
      staff: [{ chord: ["C4", "Db4", "D#4", "F#4", "G#4"], label: "♭9 ♯9 ♯11 ♭13" }], keys: ["C4", "Db4", "D#4", "F#4", "G#4"] },
    { heading: "使いどころ", key: "C",
      body: ["解決するドミナント（とくにマイナーへ向かう V7）で、緊張をぐっと強めます。"],
      staff: [{ chord: ["G3", "B3", "D4", "F4"], label: "G7" }, ch("C", "min", "Cm")] },
    { heading: "G7(♭9) の響き", key: "C",
      body: ["G B D F A♭（♭9＝A♭）。鍵盤と楽譜のアニメで確認しましょう。"],
      staff: [{ chord: ["G3", "B3", "D4", "F4", "Ab4"], label: "G7(♭9)" }],
      keys: ["G3", "B3", "D4", "F4", "Ab4"], listen: { notes: ["G3", "B3", "D4", "F4", "Ab4"], seq: false } },
    { heading: "練習：G7(♭9)", key: "G",
      body: ["G B D F A♭ を弾いて、♭9 の張りつめた緊張感を確かめましょう（マイナーへ向かう V7 で活躍）。"],
      practice: { voicings: [[0, 4, 7, 10, 13]], label: "G7(♭9)" } },
  ] },

  { title: "Part 36 オルタードテンションの性質", slides: [
    { heading: "オルタードスケール", key: "C",
      body: ["オルタードスケールは、メロディックマイナーの第7モードです。", "ドミナントのオルタードテンションが、全部そろうスケールです。"],
      staff: ["G3", "Ab3", "Bb3", "B3", "Db4", "Eb4", "F4", "G4"], keys: ["G3", "Ab3", "Bb3", "B3", "Db4", "Eb4", "F4"] },
    { heading: "テンションリゾルブ", key: "C",
      body: ["テンションは、解決先のコードの音へなめらかに進みます。", "例：♭9(A♭) は次の主音 G へ、半音で下がります。"],
      staff: ["Ab4", "G4"], staffOpts: { brackets: [{ from: 0, to: 1, text: "♭9→1" }] }, keys: ["Ab4", "G4"] },
    { heading: "♭13と♯5", key: "C",
      body: ["♭13 は増5度（♯5）と同じ音。オーギュメント系の響きとつながります。"],
      staff: [{ chord: ["G3", "B3", "D#4"], label: "Gaug (♭13)" }], keys: ["G3", "B3", "D#4"] },
    { heading: "G7(♯9) の響き", key: "C",
      body: ["G B D F A♯（♯9＝A♯）。ロックでおなじみの、力強い緊張感です。"],
      staff: [{ chord: ["G3", "B3", "D4", "F4", "A#4"], label: "G7(♯9)" }],
      keys: ["G3", "B3", "D4", "F4", "A#4"], listen: { notes: ["G3", "B3", "D4", "F4", "A#4"], seq: false } },
    { heading: "練習：G7(♯9)", key: "G",
      body: ["G B D F A♯ を弾いてみましょう。長3度と♯9が同居する、ジミヘン・コードの荒々しい響きです。"],
      practice: { voicings: [[0, 4, 7, 10, 15]], label: "G7(♯9)" } },
    { heading: "練習：オルタードスケール", key: "G",
      body: ["オルタードテンションが全部そろうスケール（G A♭ B♭ B D♭ E♭ F）。V7 の上で使えます。"],
      practice: { notes: [0, 1, 3, 4, 6, 8, 10, 12], label: "オルタードスケール" } },
  ] },

  { title: "Part 37 テンションの複合", slides: [
    { heading: "複合の基本", key: "C",
      body: ["相性のよいテンションを、組み合わせて重ねます（9th と 13th など）。"],
      staff: [{ chord: ["G3", "B3", "F4", "A4", "E5"], label: "G7(9,13)" }], keys: ["A4", "E5"] },
    { heading: "注意点", key: "C",
      body: ["アヴォイド同士や、半音でぶつかる音は避けます。", "詰め込みすぎず、音の間隔をあけて配置するのがコツです。"],
      staff: [{ chord: ["C4", "E4", "F4"], label: "半音衝突" }], keys: ["E4", "F4"] },
    { heading: "代表的な組", key: "C",
      body: ["V7(♭9,♭13)、V7(9,13)、maj7(9,13) などがよく使われます。"],
      staff: [{ chord: ["C4", "E4", "G4", "B4", "D5", "A5"], label: "maj7(9,13)" }] },
    { heading: "G7(9,13) の響き", key: "C",
      body: ["G B F A E（9＝A, 13＝E）。おだやかで洗練された響きです。"],
      staff: [{ chord: ["G3", "B3", "F4", "A4", "E5"], label: "G7(9,13)" }],
      keys: ["G3", "B3", "F4", "A4", "E5"], listen: { notes: ["G3", "B3", "F4", "A4", "E5"], seq: false } },
    { heading: "練習：G9 → G7(9,13)", key: "G",
      body: ["まず G9（G B D F A）、次に5度を抜いて13を足した G7(9,13)（G B F A E）。テンションを重ねる感覚を確かめましょう。", "（最上音の13＝E は音域が高いので、届かなければマウスでクリックしてもOKです）"],
      practice: { voicings: [[0, 4, 7, 10, 14], [0, 4, 10, 14, 21]], label: "テンションの複合（G9→G13）" } },
  ] },

  { title: "Part 38 ポリコード、アッパーストラクチャートライアド", slides: [
    { heading: "ポリコード", key: "C",
      body: ["2つのコードを上下に重ねて表す書き方を「ポリコード」といいます。", "例：D / C（下が C、上が D）。"],
      staff: [{ chord: ["C4", "E4", "G4", "D5", "F#5", "A5"], label: "D / C" }], keys: ["C4", "E4", "G4", "D5", "F#5", "A5"] },
    { heading: "アッパーストラクチャートライアド(UST)", key: "C",
      body: ["セブンスコードの上に、テンションでできる三和音を乗せる形です。", "例：D/C7＝C7(9,♯11)。上の三和音が、一気に華やかなテンションを与えます。"],
      staff: [{ chord: ["C4", "E4", "Bb4", "D5", "F#5", "A5"], label: "D / C7" }], keys: ["C4", "E4", "Bb4", "D5", "F#5", "A5"], listen: { notes: ["C4", "E4", "Bb4", "D5", "F#5", "A5"], seq: false } },
    { heading: "定番のUST（ドミナント上）", key: "C",
      body: ["ドミナント上では II（9,♯11）、♭VI（♭13,♭9）、♭II（♭9,♭5）などが定番です。"],
      staff: [{ chord: ["C4", "E4", "Bb4", "D5", "F#5", "A5"], label: "D / C7" }] },
    { heading: "D/C7 の響き", key: "C",
      body: ["下が C7、上が Dメジャー。広がりのある、豊かなテンションの響きです。"],
      staff: [{ chord: ["C4", "E4", "G4", "Bb4", "D5", "F#5", "A5"], label: "D / C7" }],
      keys: ["C4", "E4", "Bb4", "D5", "F#5", "A5"], listen: { notes: ["C4", "E4", "Bb4", "A4", "D5", "F#5"], seq: false } },
    { heading: "練習：D/C7（UST）", key: "C",
      body: ["C7 の土台（C E B♭）に、上の D の三和音（D F♯）を乗せた C7(9,♯11)。UST が一気に華やかさを与えます。"],
      practice: { voicings: [[0, 4, 10, 14, 18]], label: "D/C7＝C7(9,♯11)" } },
  ] },

  { title: "Part 39 更に特殊なテンション", slides: [
    { heading: "10th・12th・14thとは", key: "C",
      body: ["オクターブ＋3度＝10th、＋5度＝12th、＋7度＝14th。", "これらはコードの音の重複なので、ふつうはコードネームに書きません。"],
      staff: [{ chord: ["C4", "E5"], label: "10th(8+3)" }], keys: ["C4", "E5"] },
    { heading: "使う場面", key: "C",
      body: ["特別なボイシングや、響きを細かく指定したいときに、まれに登場します。"],
      staff: [{ chord: ["C4", "G5"], label: "12th(8+5)" }], keys: ["C4", "G5"] },
    { heading: "要点", key: "C",
      body: ["覚えるべき標準テンションは 9・11・13 の3つです。", "10・12・14 は「コードの音を1オクターブ上げたもの」と知っておけば十分です。"],
      staff: [{ chord: ["C4", "D5", "F5", "A5"], label: "9・11・13" }], keys: ["D5", "F5", "A5"] },
    { heading: "練習：標準テンション 9・11・13", key: "C",
      body: ["土台の C から、9th(D)・11th(F)・13th(A) を順に弾いて位置を確かめましょう。", "10・12・14 はコードトーンの重複なので、覚えるのはこの3つだけで十分です。"],
      practice: { notes: [0, 2, 5, 9], label: "9th・11th・13th（D・F・A）" } },
  ] },

  { title: "Part 40 その他の特殊なコード", slides: [
    { heading: "aug の復習", key: "C",
      body: ["オーギュメント(aug)は、長3度を2つ重ねたコードです。", "ここでは、クリシェ以外の使い方を見ていきます。"],
      staff: [{ chord: ["C4", "E4", "G#4"], label: "Caug" }], keys: ["C4", "E4", "G#4"] },
    { heading: "ドミナント代理としての aug", key: "C",
      body: ["V7 の5度を半音上げた Vaug は、強いドミナントの響きになります。", "Gaug→C のように、解決に使えます。"],
      staff: [{ chord: ["G3", "B3", "D#4"], label: "Gaug" }, { chord: ["C4", "E4", "G4"], label: "C" }],
      keys: ["G3", "B3", "D#4"], listen: { notes: ["G3", "B3", "D#4"], seq: false } },
    { heading: "分数aug（ブラックアダー／イキスギ）", key: "C",
      body: ["aug をドミナント代理にして、ルートを増4度下に置いた分数コードです。", "例：Gaug/D♭（次が C）。ベースが半音で動き、劇的な響きになります。"],
      staff: [{ chord: ["Db4", "G4", "B4", "D#5"], label: "Gaug/D♭" }], keys: ["Db4", "G4", "B4", "D#5"] },
    { heading: "練習：Gaug → C", key: "C",
      body: ["Gaug から C への、劇的な解決を弾いてみましょう。"],
      practice: { chords: [{ root: "G", type: "aug" }, { root: "C", type: "maj" }], label: "aug の解決" } },
  ] },

  // ===== コード編つづき：ドミナントセブンス徹底編（Part 41-46）=====
  { title: "Part 41 ドミナントの本質（トライトーンと5度下降）", slides: [
    { heading: "ドミナントモーションの2要素",
      example: { tempo:96, chords:[{offs:[7,11,14,17],beats:4},{offs:[0,4,7,12],beats:4}], melody:[[7,1],[11,1],[14,1],[17,1],[16,2],[12,2]], label:"V7→I（2要素の解決）" }, key: "C",
      body: ["ドミナントを使いこなす鍵は「ドミナントモーション」。これは2つの要素からできています。", "①トライトーン（三全音）の解消、②ルートの完全5度下降。この2つが進行の推進力です。"],
      staff: [ch("G", "dom7", "V7"), ch("C", "maj", "I")] },
    { heading: "トライトーン＝鍵盤6個分", key: "C",
      body: ["ドミナント7thの中の「メジャー3rd」と「マイナー7th」の間隔は、鍵盤ちょうど6個分（増4度＝減5度）。", "この宙づりの不安定な響きが、次のコードで解消される落差が原動力になります。"],
      staff: [{ chord: ["G3", "B3", "D4", "F4"], label: "G7" }, { chord: ["B3", "F4"], label: "3rd・♭7th＝6個分" }],
      keys: ["B3", "F4"] },
    { heading: "トライトーンの解消", key: "C",
      body: ["G7 の「シ(B)」と「ファ(F)」が、次の C の「ド(C)」「ミ(E)」へ半音で吸い込まれます。", "B→C（外へ）、F→E（内へ）。この2音の解決が、あらゆる終止感の核です。"],
      staff: [{ chord: ["B3", "F4"], label: "シ・ファ" }, { chord: ["C4", "E4"], label: "ド・ミ" }],
      keys: ["B3", "F4", "C4", "E4"] },
    { heading: "ルートの完全5度下降", key: "C",
      body: ["もう一つの要素は、ルートが5度下（＝4度上）のコードへ動くこと。G→C がこれです。", "「コードが変わった」という強い実感は、この5度下降から生まれます。"],
      staff: [ch("G", "dom7", "G7"), ch("C", "maj", "C")], keys: ["G3", "C4"] },
    { heading: "練習：G7 → C（2要素を体感）", key: "C",
      body: ["トライトーンの解消とルート5度下降。両方を感じながら G7→C を弾いてみましょう。"],
      practice: { chords: [{ root: "G", type: "dom7" }, { root: "C", type: "maj" }], label: "ドミナントモーション" } },
    { heading: "練習：トライトーンの解消だけ", key: "C",
      body: ["G7 の核＝ファ＋シだけを弾き、次に ミ＋ド へ。2音が半音で解決する瞬間を取り出して確かめます。"],
      practice: { voicings: [[5, 11], [4, 12]], label: "ファ・シ→ミ・ド" } },
  ] },

  { title: "Part 42 いろいろなドミナント", slides: [
    { heading: "プライマリードミナント", key: "C",
      body: ["キーの中に最初から在るドミナント7th、それが V7（プライマリードミナント）。", "Cメジャーなら G7。ダイアトニックコード唯一のドミナント7thです。"],
      staff: [ch("G", "dom7", "V7＝G7"), ch("C", "maj", "I")] },
    { heading: "セカンダリードミナント（復習）", key: "C",
      body: ["キーの外からドミナントを借り、ダイアトニックの各コードへドミナントモーションさせる手法。", "例：G(V)へ向かう D7（＝V7/V）。くわしくは Part 23。"],
      staff: [ch("D", "dom7", "V7/V"), ch("G", "maj", "V")] },
    { heading: "ドッペルドミナント（ダブルドミナント）",
      example: { tempo:120, chords:[{offs:[2,6,9,12],beats:2},{offs:[7,11,14,17],beats:2},{offs:[0,4,7],beats:4}], melody:[[2,1],[6,1],[7,1],[11,1],[12,2],[7,1],[11,1],[12,2]], label:"D7→G7→C" }, key: "C",
      body: ["進行先もドミナント7thになっている状態。濁った響きが連続するのが特徴です。", "D7→G7→C。V7/V の解決先 G を、さらに G7 にして C へ。ドミナントが2つ連なります。"],
      staff: [ch("D", "dom7", "V7/V"), ch("G", "dom7", "V7"), ch("C", "maj", "I")] },
    { heading: "エクステンデッドドミナント",
      example: { tempo:132, chords:[{offs:[4,8,11,14],beats:2},{offs:[9,13,16,19],beats:2},{offs:[2,6,9,12],beats:2},{offs:[7,11,14,17],beats:2},{offs:[0,4,7],beats:4}], melody:[[4,1],[9,1],[14,1],[19,1],[16,2],[12,2],[7,2],[0,2]], label:"E7→A7→D7→G7→C" }, key: "C",
      body: ["終着点から逆算し、ドミナントモーションを3連・4連と遡って繋げる手法。", "E7→A7→D7→G7→C。5度下降でドミナント7thが数珠つなぎになります。"],
      staff: [ch("E", "dom7", "E7"), ch("A", "dom7", "A7"), ch("D", "dom7", "D7"), ch("G", "dom7", "G7"), ch("C", "maj", "C")] },
    { heading: "テンション入りドミナント", key: "C",
      body: ["ナチュラル系（9,13）やオルタード系（♭9,♯9,♯11,♭13）を足して響きを濁らせ、解決時のコントラストを強めます。", "詳しくは Part 35〜37。"],
      staff: [{ chord: ["G3", "B3", "F4", "A4", "E5"], label: "G7(9,13)" }], keys: ["A4", "E5"] },
    { heading: "練習：ドッペルドミナント", key: "C",
      body: ["ドミナント7thが2つ連なる D7→G7→C を弾いてみましょう。"],
      practice: { chords: [{ root: "D", type: "dom7" }, { root: "G", type: "dom7" }, { root: "C", type: "maj" }], label: "ドッペルドミナント" } },
    { heading: "練習：エクステンデッドドミナント", key: "C",
      body: ["ドミナントを4連続で数珠つなぎ。E7→A7→D7→G7→C を弾いてみましょう。"],
      practice: { chords: [{ root: "E", type: "dom7" }, { root: "A", type: "dom7" }, { root: "D", type: "dom7" }, { root: "G", type: "dom7" }, { root: "C", type: "maj" }], label: "エクステンデッドドミナント" } },
  ] },

  { title: "Part 43 偽終止とピカルディ終止", slides: [
    { heading: "偽終止（デセプティブ・ケイデンス）",
      example: { tempo:104, chords:[{offs:[7,11,14,17],beats:4},{offs:[9,12,16],beats:4}], melody:[[7,1],[11,1],[14,1],[11,1],[12,1],[9,2]], label:"V7→VIm（裏切り）" }, key: "C",
      body: ["期待される解決先（I）を裏切り、別のコードへ進むテクニック。", "V7 から、トニックの代理コード（VIm や IIIm）へ。G7→Am、G7→Em。"],
      staff: [ch("G", "dom7", "V7"), ch("A", "min", "VIm")] },
    { heading: "セカンダリードミナントの偽終止", key: "C",
      body: ["セカンダリードミナントでも同じ裏切りができます。本来の解決先ではなく、その代理コードへ。", "例：C7（＝V7/IV）は F(IV) へ行くはず。それを IIm（F の代理 Dm）へすり替えます。"],
      staff: [ch("C", "dom7", "V7/IV"), ch("D", "min", "IIm（Fの代理）")] },
    { heading: "ピカルディ終止",
      example: { tempo:92, chords:[{offs:[0,3,7],beats:2},{offs:[5,8,12],beats:2},{offs:[7,11,14,17],beats:2},{offs:[0,4,7],beats:4}], melody:[[0,1],[7,1],[8,2],[11,1],[12,1],[11,2],[4,3]], label:"Am…→A（ピカルディ）" }, key: "A",
      body: ["マイナーキーの曲で、最後を強引にメジャーコードに変えて終わらせる手法。", "Aマイナーの終わりを Am ではなく A（メジャー）に。暗い曲が最後だけ晴れやかに解決します。"],
      staff: [ch("E", "dom7", "E7"), ch("A", "maj", "A（ピカルディ）")], keys: ["A3", "C#4", "E4"] },
    { heading: "練習：偽終止 G7→Am", key: "C",
      body: ["I へ解決すると思わせて VIm へ。G7→Am のはぐらかしを弾いてみましょう。"],
      practice: { chords: [{ root: "G", type: "dom7" }, { root: "A", type: "min" }], label: "偽終止 V7→VIm" } },
    { heading: "練習：セカンダリの偽終止 C7→Dm", key: "C",
      body: ["C7（V7/IV）を、本来の F ではなく代理の Dm へ。狙いを外す響きを味わいましょう。"],
      practice: { chords: [{ root: "C", type: "dom7" }, { root: "D", type: "min" }], label: "セカンダリの偽終止" } },
    { heading: "練習：ピカルディ終止 E7→A", key: "C",
      body: ["マイナーの流れから、最後だけメジャーの A へ。E7→A の晴れやかな解決を弾いてみましょう。"],
      practice: { chords: [{ root: "E", type: "dom7" }, { root: "A", type: "maj" }], label: "ピカルディ終止" } },
  ] },

  { title: "Part 44 特殊な構造（7sus4・ハイブリッド）", slides: [
    { heading: "サスペンデッド・ドミナント（7sus4）", key: "C",
      body: ["7sus4 は3rdの代わりに4thを使うため、トライトーンを含みません。本来のドミナントの定義からは外れます。", "しかし現代では、前後関係（文脈）からドミナントの代わりとして扱われます。G7sus4→C。"],
      staff: [{ chord: ["G3", "C4", "D4", "F4"], label: "G7sus4" }, ch("C", "maj", "C")],
      keys: ["G3", "C4", "D4", "F4"] },
    { heading: "7sus4 の解決", key: "C",
      body: ["4th(C) を 3rd(B) へ動かせば G7 に戻り、そのまま C へ解決。動かさず sus のまま次へ進んでもOK。", "宙づり→着地の落差が、やわらかいドミナントの魅力です。"],
      staff: [{ chord: ["G3", "C4", "D4", "F4"], label: "G7sus4" }, { chord: ["G3", "B3", "D4", "F4"], label: "G7" }, ch("C", "maj", "C")] },
    { heading: "ハイブリッドコード（フュージョンコード）", key: "C",
      body: ["ルートの全音下のメジャーコードを上に乗せる手法（IV/V など）。", "G の全音下＝F。F/G のように重ねると、よりリッチで現代的な響きになります。"],
      staff: [{ chord: ["G3", "F4", "A4", "C5"], label: "F/G (IV/V)" }], keys: ["G3", "F4", "A4", "C5"] },
    { heading: "練習：G7sus4 → C", key: "C",
      body: ["3度を持たない宙づりの sus から、C へ解決する流れを弾いてみましょう。"],
      practice: { chords: [{ root: "G", type: "sus4" }, { root: "C", type: "maj" }], label: "サスペンデッド・ドミナント" } },
    { heading: "練習：F/G → C（ハイブリッド）", key: "G",
      body: ["G の上に F の三和音を重ねた F/G（G・F・A・C）→ C。リッチで現代的な解決です。"],
      practice: { voicings: [[0, 10, 14, 17], [5, 9, 12]], label: "ハイブリッド F/G → C" } },
  ] },

  { title: "Part 45 スペシャルファンクション・ドミナント", slides: [
    { heading: "スペシャルファンクションとは", key: "C",
      body: ["ドミナントモーション（5度下降）のルールに従わない、特殊な役割を持つドミナント7thたち。", "代表は6つ：I7・IV7・♭VII7・♭VI7・II7・VII7。多くはトニックへ直接進めます。"],
      staff: [ch("C", "dom7", "I7"), ch("F", "dom7", "IV7"), ch("A#", "dom7", "♭VII7")] },
    { heading: "I7（トニックの7th化）",
      example: { tempo:96, chords:[{offs:[0,4,7,10],beats:4},{offs:[5,9,12,15],beats:2},{offs:[0,4,7,10],beats:2}], melody:[[0,1],[3,0.5],[4,0.5],[7,1],[10,1],[7,0.5],[3,0.5],[0,2]], label:"I7-IV7-I7（ブルース）" }, key: "C",
      body: ["トニック I をセブンス化した C7。ブルースのような「ホット」で土くさい雰囲気になります。", "本来は不安定なはずの7thを、あえて安定の座（I）に置くのがミソ。"],
      staff: [ch("C", "dom7", "I7＝C7")] },
    { heading: "IV7（サブドミナントの7th化）", key: "C",
      body: ["サブドミナント IV をセブンス化した F7。ブルースで I7 と並んで多用されます。"],
      staff: [ch("F", "dom7", "IV7＝F7")] },
    { heading: "♭VII7 → I（直進ドミナント）", key: "C",
      body: ["♭VII7（B♭7）は、トニック I へ直進できる非常に有名で使いやすいコード。", "ミクソリディアン的な、力強くもどこか懐かしい解決です。"],
      staff: [ch("A#", "dom7", "♭VII7"), ch("C", "maj", "I")] },
    { heading: "♭VI7 → I", key: "C",
      body: ["♭VI7（A♭7）も、トニックへ直進できます。裏コードにも通じる、半音の色気を持つ濃い響き。"],
      staff: [ch("G#", "dom7", "♭VI7"), ch("C", "maj", "I")] },
    { heading: "II7（同じ形でも役割ちがい）", key: "C",
      body: ["II7（D7）はドッペルドミナントと同じ形。ただしここでは5度下降せず、I などへ進む使い方を指します。", "同じコードでも「どこへ進むか」で役割が変わります。"],
      staff: [ch("D", "dom7", "II7"), ch("C", "maj", "I")] },
    { heading: "VII7", key: "C",
      body: ["VII7（B7）は IV7 の代理的な役割で使われ、トニックへ進むことができます。"],
      staff: [ch("B", "dom7", "VII7"), ch("C", "maj", "I")] },
    { heading: "練習：♭VII7 → I", key: "C",
      body: ["トニックへ直進する定番、B♭7→C を弾いてみましょう。"],
      practice: { chords: [{ root: "A#", type: "dom7" }, { root: "C", type: "maj" }], label: "♭VII7→I" } },
    { heading: "練習：I7 → IV7（ブルース）", key: "C",
      body: ["トニックもサブドミナントも7th化。C7→F7 のホットなブルース感を弾いてみましょう。"],
      practice: { chords: [{ root: "C", type: "dom7" }, { root: "F", type: "dom7" }, { root: "C", type: "dom7" }], label: "I7-IV7-I7" } },
    { heading: "練習：♭VI7 → I", key: "C",
      body: ["もう一つの直進ドミナント、A♭7→C を弾いてみましょう。"],
      practice: { chords: [{ root: "G#", type: "dom7" }, { root: "C", type: "maj" }], label: "♭VI7→I" } },
  ] },

  { title: "Part 46 高度な応用テクニック", slides: [
    { heading: "整列式2連続ドミナント",
      example: { tempo:120, chords:[{offs:[7,11,14,17],beats:2},{offs:[1,5,8,11],beats:2},{offs:[0,4,7],beats:4}], melody:[[7,1],[11,1],[8,2],[11,1],[12,1],[16,2]], label:"G7→D♭7→C（表と裏）" }, key: "C",
      body: ["ドミナントの枠を、同じ解決先を持つ2つのコード（表と裏）に分割して並べる手法。", "G7（表）と D♭7（裏）はどちらも C へ解決。G7→D♭7→C と2つ並べて置きます。"],
      staff: [ch("G", "dom7", "G7(表)"), ch("C#", "dom7", "D♭7(裏)"), ch("C", "maj", "C")] },
    { heading: "オルタレーション", key: "C",
      body: ["コードの構成音（主にテンション）を意図的に変化させ、聴き手の意外性を突く効果。", "例：素直な G7 を G7(♭9,♯9) に変え、緊張を跳ね上げてから解決させます。"],
      staff: [{ chord: ["G3", "B3", "F4", "Ab4", "A#4"], label: "G7(♭9,♯9)" }], keys: ["Ab4", "A#4"] },
    { heading: "非機能的・適当な配置",
      example: { tempo:100, chords:[{offs:[0,4,7,10],beats:2},{offs:[3,7,10,13],beats:2},{offs:[6,10,13,16],beats:2},{offs:[9,13,16,19],beats:2}], melody:[[0,2],[3,2],[6,2],[9,2]], label:"平行ドミナントの浮遊感" }, key: "C",
      body: ["音楽的なルール（スキーマ）をあえて無視してドミナントを置く手法。", "調の中心をぼかし、独特の浮遊感や雰囲気を作ります。例：C7→E♭7→F♯7→A7 と短3度で平行移動。"],
      staff: [ch("C", "dom7", "C7"), ch("D#", "dom7", "E♭7"), ch("F#", "dom7", "F♯7"), ch("A", "dom7", "A7")] },
    { heading: "練習：整列式2連続 G7→D♭7→C", key: "C",
      body: ["同じ C へ解決する表と裏を並べた G7→D♭7→C。ベースが半音で下る流れを弾いてみましょう。"],
      practice: { chords: [{ root: "G", type: "dom7" }, { root: "C#", type: "dom7" }, { root: "C", type: "maj" }], label: "整列式2連続ドミナント" } },
    { heading: "練習：非機能パラレルドミナント", key: "C",
      body: ["短3度ずつ平行移動する C7→E♭7→F♯7→A7。調性をぼかす浮遊感を体感しましょう。"],
      practice: { chords: [{ root: "C", type: "dom7" }, { root: "D#", type: "dom7" }, { root: "F#", type: "dom7" }, { root: "A", type: "dom7" }], label: "非機能パラレルドミナント" } },
  ] },

  // ===== リズム編（Part 47-52）=====
  // rhythm スライドは下の「▶ リズムを再生」で拍位置のクリック音を鳴らす（beats=1小節の拍数, hitsは拍位置0.0〜）。
  { title: "Part 47 拍と拍子", chapter: "リズム編", slides: [
    { heading: "拍（ビート）とは", key: "C",
      body: ["音楽の時間を刻む等間隔のパルスが「拍（ビート）」。手拍子や足踏みのタイミングです。", "下のグリッドが1拍ずつ光り、1拍目にアクセントが付きます。"],
      rhythm: { tempo: 96, beats: 4, bars: 1, grid: 4, loop: 2, layers: [{ name: "拍", pitch: "C5", accentPitch: "C6", hits: [0, 1, 2, 3], accents: [0] }] } },
    { heading: "4/4拍子", key: "C",
      body: ["拍を4つずつまとめたのが「4/4拍子」。ポップスの大多数がこれです。", "強・弱・中強・弱（1拍目が強拍、3拍目が中強拍）という重みの階層があります。"],
      rhythm: { tempo: 100, beats: 4, bars: 1, grid: 4, loop: 2, layers: [{ name: "4/4", pitch: "C5", accentPitch: "C6", hits: [0, 1, 2, 3], accents: [0, 2] }] } },
    { heading: "3/4拍子（ワルツ）", key: "C",
      body: ["3拍で1周する拍子。「強・弱・弱」でくり返す、ワルツの優雅な揺れです。"],
      rhythm: { tempo: 132, beats: 3, bars: 1, grid: 4, loop: 3, layers: [{ name: "3/4", pitch: "C5", accentPitch: "C6", hits: [0, 1, 2], accents: [0] }] } },
    { heading: "2/4拍子（マーチ）", key: "C",
      body: ["2拍で1周する拍子。「強・弱」でくり返す、行進やサンバのノリです。"],
      rhythm: { tempo: 108, beats: 2, bars: 1, grid: 4, loop: 4, layers: [{ name: "2/4", pitch: "C5", accentPitch: "C6", hits: [0, 1], accents: [0] }] } },
    { heading: "キックとスネアの基本", key: "C",
      body: ["ドラムの土台は、1・3拍目のキック（低）と、2・4拍目のスネア（高）。", "この組み合わせが、ロックやポップスの基本ビートです。"],
      rhythm: { tempo: 100, beats: 4, bars: 1, grid: 4, loop: 2, layers: [
        { name: "キック", pitch: "C2", hits: [0, 2] },
        { name: "スネア", pitch: "A3", hits: [1, 3] },
      ] } },
  ] },

  { title: "Part 48 ビートとサブディビジョン", slides: [
    { heading: "サブディビジョン（拍の分割）", key: "C",
      body: ["1拍をさらに等分することを「サブディビジョン」といいます。", "1拍を2分割＝8分（8ビート）、4分割＝16分（16ビート）。細かいほど疾走感が出ます。"],
      rhythm: { tempo: 96, beats: 4, bars: 1, grid: 4, loop: 2, layers: [{ name: "拍", pitch: "C5", accentPitch: "C6", hits: [0, 1, 2, 3], accents: [0] }] } },
    { heading: "8ビート", key: "C",
      body: ["1拍を2分割し、8分音符でハイハットを刻むのが8ビート。ロック／ポップスの定番です。"],
      rhythm: { tempo: 100, beats: 4, bars: 1, grid: 4, loop: 2, layers: [
        { name: "ハイハット", pitch: "F#5", hits: [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5] },
        { name: "キック", pitch: "C2", hits: [0, 2] },
        { name: "スネア", pitch: "A3", hits: [1, 3] },
      ] } },
    { heading: "16ビート", key: "C",
      body: ["1拍を4分割して刻むのが16ビート。ファンクやR&Bの細かくうねるノリです。"],
      rhythm: { tempo: 92, beats: 4, bars: 1, grid: 4, loop: 2, layers: [
        { name: "16分", pitch: "F#5", accentPitch: "F#6", hits: [0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 2.75, 3, 3.25, 3.5, 3.75], accents: [0, 1, 2, 3] },
      ] } },
    { heading: "表拍と裏拍", key: "C",
      body: ["1拍の前半が「表拍（ダウンビート）」、後半が「裏拍（アップビート）」。", "裏拍を強調すると軽快で浮遊感のあるノリ（テクノ／ディスコ）になります。"],
      rhythm: { tempo: 104, beats: 4, bars: 1, grid: 4, loop: 2, layers: [
        { name: "表拍", pitch: "C5", hits: [0, 1, 2, 3] },
        { name: "裏拍", pitch: "F#5", hits: [0.5, 1.5, 2.5, 3.5] },
      ] } },
    { heading: "四つ打ち＋裏ハイハット", key: "C",
      body: ["全拍でキックを打つ「四つ打ち」に、裏拍のハイハットを重ねるとダンス系のノリに。"],
      rhythm: { tempo: 124, beats: 4, bars: 1, grid: 4, loop: 2, layers: [
        { name: "キック", pitch: "C2", hits: [0, 1, 2, 3] },
        { name: "ハイハット", pitch: "F#5", hits: [0.5, 1.5, 2.5, 3.5] },
      ] } },
  ] },

  { title: "Part 49 強拍とシンコペーション", slides: [
    { heading: "強拍・弱拍・中強拍", key: "C",
      body: ["4/4では1拍目＝強拍、3拍目＝中強拍、2・4拍目＝弱拍という重みの階層があります。"],
      rhythm: { tempo: 96, beats: 4, bars: 1, grid: 4, loop: 2, layers: [{ name: "重み", pitch: "C5", accentPitch: "C6", hits: [0, 1, 2, 3], accents: [0, 2] }] } },
    { heading: "バックビート", key: "C",
      body: ["本来弱い2・4拍目にスネアで強いアクセントを置くのが「バックビート」。", "ロック／ソウルの推進力の源です。"],
      rhythm: { tempo: 100, beats: 4, bars: 1, grid: 4, loop: 2, layers: [
        { name: "キック", pitch: "C2", hits: [0, 2] },
        { name: "スネア", pitch: "A3", accentPitch: "A4", hits: [1, 3], accents: [1, 3] },
      ] } },
    { heading: "シンコペーション", key: "C",
      body: ["拍の重みがない位置（裏拍など）にアクセントを置く技法。", "前のめりの緊張が生まれ、強拍へ戻ると解決します。下は表拍とシンコペの比較です。"],
      rhythm: { tempo: 96, beats: 4, bars: 1, grid: 4, loop: 2, layers: [
        { name: "オンビート", pitch: "C5", hits: [0, 1, 2, 3] },
        { name: "シンコペ", pitch: "E5", accentPitch: "E6", hits: [0, 1.5, 2.5], accents: [1.5, 2.5] },
      ] } },
    { heading: "「移民の歌」風", key: "C",
      body: ["4拍目の16分裏にキックを突っ込む、前のめりな有名パターン（ダドンッ）。"],
      rhythm: { tempo: 108, beats: 4, bars: 1, grid: 4, loop: 2, layers: [
        { name: "キック", pitch: "C2", accentPitch: "C3", hits: [0, 1, 2, 3, 3.75], accents: [3.75] },
        { name: "スネア", pitch: "A3", hits: [1, 3] },
      ] } },
  ] },

  { title: "Part 50 クラーヴェ", slides: [
    { heading: "トレシーロ（3-3-2）", key: "C",
      body: ["1小節の8分音符を 3+3+2 でグループ化したラテンの基本リズム。", "打点は 0・1.5・3拍目。ラテン／レゲトン／ポップスに広く使われます。"],
      rhythm: { tempo: 100, beats: 4, bars: 1, grid: 2, loop: 2, layers: [{ name: "3-3-2", pitch: "E5", accentPitch: "E6", hits: [0, 1.5, 3], accents: [0] }] } },
    { heading: "ソン・クラーベ（3-2）", key: "C",
      body: ["2小節で1周するラテンの核。1小節目に3打（トレシーロ側）、2小節目に2打。", "ラテン音楽全体の『ものさし』となるリズムです。"],
      rhythm: { tempo: 100, beats: 4, bars: 2, grid: 2, loop: 2, layers: [{ name: "クラーベ", pitch: "E5", accentPitch: "E6", hits: [0, 1.5, 3, 5, 6], accents: [0] }] } },
    { heading: "ソン・クラーベ（2-3）", key: "C",
      body: ["3-2 を前後反転したもの。1小節目の頭が空くので、大人っぽく落ち着いた出だしに。"],
      rhythm: { tempo: 100, beats: 4, bars: 2, grid: 2, loop: 2, layers: [{ name: "クラーベ", pitch: "E5", accentPitch: "E6", hits: [1, 2, 4, 5.5, 7], accents: [4] }] } },
    { heading: "ボサ・クラーベ", key: "C",
      body: ["ソン・クラーベの2打側の後打を『3拍目の裏』へずらし、シンコペを強めたもの。", "ボサノヴァのしなやかな揺れが生まれます。"],
      rhythm: { tempo: 108, beats: 4, bars: 2, grid: 2, loop: 2, layers: [{ name: "ボサ", pitch: "E5", accentPitch: "E6", hits: [0, 1.5, 3, 5, 6.5], accents: [0] }] } },
  ] },

  { title: "Part 51 シャッフルと複合拍子", slides: [
    { heading: "三連符", key: "C",
      body: ["1拍を3等分したのが三連符。ジャズやブルースの『跳ねる』土台になります。"],
      rhythm: { tempo: 92, beats: 4, bars: 1, grid: 3, loop: 2, layers: [{ name: "三連", pitch: "F#5", accentPitch: "F#6", hits: [0, 0.333, 0.667, 1, 1.333, 1.667, 2, 2.333, 2.667, 3, 3.333, 3.667], accents: [0, 1, 2, 3] }] } },
    { heading: "シャッフル", key: "C",
      body: ["三連符の1音目と3音目だけを鳴らす（2:1の比）と、『タッカ タッカ』と跳ねます。", "低いテンポほど跳ねが強く、速いテンポでは等分割に近づきます。"],
      rhythm: { tempo: 92, beats: 4, bars: 1, grid: 3, loop: 2, layers: [
        { name: "シャッフル", pitch: "F#5", hits: [0, 0.667, 1, 1.667, 2, 2.667, 3, 3.667] },
        { name: "スネア", pitch: "A3", hits: [1, 3] },
      ] } },
    { heading: "6/8拍子（複合拍子）", key: "C",
      body: ["8分音符6つを『3＋3』にまとめた拍子。大きく2拍・中で3分割の二重構造です。", "1つ目と4つ目の8分にアクセント（付点4分が2つ）。"],
      rhythm: { tempo: 120, beats: 6, bars: 1, grid: 2, loop: 2, layers: [{ name: "6/8", pitch: "C5", accentPitch: "C6", hits: [0, 1, 2, 3, 4, 5], accents: [0, 3] }] } },
    { heading: "ハーフタイム・シャッフル", key: "C",
      body: ["シャッフルのままスネアを半分に減らし（3拍目のみ）、どっしり遅く感じさせる技法。"],
      rhythm: { tempo: 92, beats: 4, bars: 1, grid: 3, loop: 2, layers: [
        { name: "シャッフル", pitch: "F#5", hits: [0, 0.667, 1, 1.667, 2, 2.667, 3, 3.667] },
        { name: "スネア", pitch: "A3", accentPitch: "A4", hits: [2], accents: [2] },
      ] } },
  ] },

  { title: "Part 52 ポリリズムと変拍子", slides: [
    { heading: "ポリリズム 3:2", key: "C",
      body: ["同じ長さの中で、一方が3等分・もう一方が2等分を同時に鳴らすのが「ポリリズム」。", "3:2 は最も基本的で、ヘミオラとも呼ばれます。"],
      rhythm: { tempo: 90, beats: 2, bars: 1, grid: 3, loop: 3, layers: [
        { name: "2の層", pitch: "C5", accentPitch: "C6", hits: [0, 1], accents: [0] },
        { name: "3の層", pitch: "F#5", accentPitch: "F#6", hits: [0, 0.667, 1.333], accents: [0] },
      ] } },
    { heading: "ポリリズム 4:5", key: "C",
      body: ["4の層と5の層を重ねると、20分割で1周する複雑なうねり（Perfume『ポリリズム』風）。"],
      rhythm: { tempo: 100, beats: 4, bars: 1, grid: 5, loop: 2, layers: [
        { name: "4の層", pitch: "C5", accentPitch: "C6", hits: [0, 1, 2, 3], accents: [0] },
        { name: "5の層", pitch: "F#5", accentPitch: "F#6", hits: [0, 0.8, 1.6, 2.4, 3.2], accents: [0] },
      ] } },
    { heading: "変拍子 5/4（3+2）", key: "C",
      body: ["5拍を『3＋2』にグループ分けした変拍子。総拍数よりアクセントの位置が大切です。"],
      rhythm: { tempo: 120, beats: 5, bars: 1, grid: 2, loop: 2, layers: [{ name: "5/4", pitch: "C5", accentPitch: "C6", hits: [0, 1, 2, 3, 4], accents: [0, 3] }] } },
    { heading: "変拍子 7/8（2+2+3）", key: "C",
      body: ["8分音符7つを『2＋2＋3』に分けた変拍子。頭を強調しフレーズを反復して馴染ませます。"],
      rhythm: { tempo: 150, beats: 7, bars: 1, grid: 2, loop: 2, layers: [{ name: "7/8", pitch: "C5", accentPitch: "C6", hits: [0, 1, 2, 3, 4, 5, 6], accents: [0, 2, 4] }] } },
  ] },
];
